In [2]:
# import libraries
import pandas as pd
from datetime import datetime
import numpy as np

In [3]:
# Open CSV
csvdf = pd.read_csv('SEHK_2_clean.csv') 
csvdf = csvdf[csvdf['Volume'] != 0] 
csvdf

,Name,Date,Open,High,Low,Close,Volume,Count,VWAP
0,2,30/4/2007 02:00,59.05,59.05,58.50,58.50,5000,6,58.6550
1,2,30/4/2007 02:01,58.50,58.50,58.50,58.50,1000,1,58.5000
5,2,30/4/2007 02:05,58.35,58.35,58.35,58.35,2000,1,58.3500
8,2,30/4/2007 02:08,58.40,58.40,58.40,58.40,25000,1,58.4000
9,2,30/4/2007 02:09,58.35,58.40,58.35,58.40,3000,2,58.3667
12,2,30/4/2007 02:12,58.40,58.40,58.40,58.40,15000,1,58.4000
15,2,30/4/2007 02:15,58.35,58.35,58.35,58.35,4500,2,58.3500
17,2,30/4/2007 02:17,58.35,58.35,58.35,58.35,2000,1,58.3500
18,2,30/4/2007 02:18,58.30,58.30,58.20,58.20,6000,3,58.2667
19,2,30/4/2007 02:19,58.25,58.25,58.25,58.25,2500,1,58.2500
21,2,30/4/2007 02:21,58.20,58.20,58.10,58.10,25000,4,58.1940
22,2,30/4/2007 02:22,58.10,58.10,58.10,58.10,22500,3,58.1000
23,2,30/4/2007 02:23,58.10,58.15,58.00,58.15,110000,3,58.1032
24,2,30/4/2007 02:24,58.10,58.10,58.10,58.10,2000,1,58.1000
25,2,30/4/2007 02:25,58.10,58.10,58.00,58.00,18000,3,58.0194
26,2,30/4/2007 02:26,58.10,58.10,58.10,58.10,1282,2,58.1000
28,2,30/4/2007 02:28,58.10,58.10,58.10,58.10,20000,1,58.1000
29,2,30/4/2007 02:29,58.10,58.10,58.10,58.10,5000,1,58.1000
30,2,30/4/2007 02:30,58.05,58.05,58.05,58.05,2000,1,58.0500
31,2,30/4/2007 02:31,58.05,58.05,58.05,58.05,12000,1,58.0500
32,2,30/4/2007 02:32,58.05,58.05,58.05,58.05,3500,2,58.0500
33,2,30/4/2007 02:33,58.10,58.10,58.10,58.10,1000,1,58.1000
38,2,30/4/2007 02:38,58.10,58.10,58.10,58.10,8000,2,58.1000
40,2,30/4/2007 02:40,58.10,58.10,58.05,58.10,82000,3,58.0988
41,2,30/4/2007 02:41,58.10,58.10,58.10,58.10,5000,4,58.1000
42,2,30/4/2007 02:42,58.10,58.10,58.05,58.05,10500,3,58.0833
43,2,30/4/2007 02:43,58.05,58.05,58.00,58.00,25500,9,58.0245
44,2,30/4/2007 02:44,58.00,58.05,58.00,58.00,21500,4,58.0012
45,2,30/4/2007 02:45,58.00,58.00,57.80,57.80,74500,9,57.8916
46,2,30/4/2007 02:46,57.80,57.80,57.40,57.40,54500,16,57.6353
...,...,...,...,...,...,...,...,...,...
824195,2,31/7/2018 07:31,88.85,88.85,88.80,88.85,3000,4,88.8417
824196,2,31/7/2018 07:32,88.85,88.90,88.80,88.90,25500,29,88.8569
824197,2,31/7/2018 07:33,88.90,88.90,88.90,88.90,2500,3,88.9000
824198,2,31/7/2018 07:34,88.90,88.90,88.90,88.90,500,1,88.9000
824199,2,31/7/2018 07:35,88.90,88.90,88.85,88.85,5500,7,88.8864
824200,2,31/7/2018 07:36,88.90,88.90,88.90,88.90,2500,3,88.9000
824201,2,31/7/2018 07:37,88.90,88.90,88.90,88.90,1500,3,88.9000
824202,2,31/7/2018 07:38,88.90,88.90,88.85,88.90,4500,7,88.8889
824203,2,31/7/2018 07:39,88.85,89.00,88.85,89.00,171000,40,88.9180
824204,2,31/7/2018 07:40,89.00,89.00,88.95,89.00,10500,6,88.9619
824205,2,31/7/2018 07:41,89.00,89.00,88.95,89.00,3500,5,88.9929
824206,2,31/7/2018 07:42,89.00,89.00,89.00,89.00,10000,5,89.0000
824207,2,31/7/2018 07:43,89.00,89.00,88.95,89.00,2000,4,88.9875
824208,2,31/7/2018 07:44,88.95,89.00,88.95,89.00,139500,65,88.9914
824209,2,31/7/2018 07:45,89.00,89.20,89.00,89.20,88000,45,89.0889
824210,2,31/7/2018 07:46,89.20,89.20,89.20,89.20,8500,6,89.2000
824211,2,31/7/2018 07:47,89.20,89.25,89.20,89.25,9000,10,89.2028
824212,2,31/7/2018 07:48,89.20,89.20,89.15,89.20,30500,19,89.1836
824213,2,31/7/2018 07:49,89.25,89.25,89.25,89.25,11000,11,89.2500
824214,2,31/7/2018 07:50,89.25,89.30,89.25,89.30,11000,15,89.2909
824215,2,31/7/2018 07:51,89.30,89.40,89.30,89.40,121000,54,89.3465
824216,2,31/7/2018 07:52,89.40,89.40,89.35,89.40,23000,26,89.3870
824217,2,31/7/2018 07:53,89.40,89.45,89.40,89.45,102500,45,89.4110
824218,2,31/7/2018 07:54,89.45,89.45,89.45,89.45,3500,7,89.4500
824219,2,31/7/2018 07:55,89.45,89.50,89.45,89.50,19000,23,89.4724
824220,2,31/7/2018 07:56,89.50,89.50,89.35,89.50,156500,48,89.4534
824221,2,31/7/2018 07:57,89.50,89.50,89.40,89.40,4500,7,89.4389
824222,2,31/7/2018 07:58,89.45,89.50,89.45,89.50,15500,13,89.4677
824223,2,31/7/2018 07:59,89.45,89.70,89.45,89.70,161000,100,89.5789
824232,2,31/7/2018 08:08,89.65,89.65,89.65,89.65,901000,177,89.6500

In [4]:
# Set index to Date TimeSeries

csvdf['Date'] = pd.to_datetime(csvdf['Date'], dayfirst=True)
csvdf.set_index('Date', inplace=True)

In [148]:
SEHK_2_df = csvdf[:'2018'].copy()
SEHK_2_df

                     Name   Open   High    Low  Close  Volume  Count     VWAP
Date
2007-04-30 02:00:00     2  59.05  59.05  58.50  58.50    5000      6  58.6550
2007-04-30 02:01:00     2  58.50  58.50  58.50  58.50    1000      1  58.5000
2007-04-30 02:05:00     2  58.35  58.35  58.35  58.35    2000      1  58.3500
2007-04-30 02:08:00     2  58.40  58.40  58.40  58.40   25000      1  58.4000
2007-04-30 02:09:00     2  58.35  58.40  58.35  58.40    3000      2  58.3667
2007-04-30 02:12:00     2  58.40  58.40  58.40  58.40   15000      1  58.4000
2007-04-30 02:15:00     2  58.35  58.35  58.35  58.35    4500      2  58.3500
2007-04-30 02:17:00     2  58.35  58.35  58.35  58.35    2000      1  58.3500
2007-04-30 02:18:00     2  58.30  58.30  58.20  58.20    6000      3  58.2667
2007-04-30 02:19:00     2  58.25  58.25  58.25  58.25    2500      1  58.2500
2007-04-30 02:21:00     2  58.20  58.20  58.10  58.10   25000      4  58.1940
2007-04-30 02:22:00     2  58.10  58.10  58.10  58.10   22500      3  58.1000
2007-04-30 02:23:00     2  58.10  58.15  58.00  58.15  110000      3  58.1032
2007-04-30 02:24:00     2  58.10  58.10  58.10  58.10    2000      1  58.1000
2007-04-30 02:25:00     2  58.10  58.10  58.00  58.00   18000      3  58.0194
2007-04-30 02:26:00     2  58.10  58.10  58.10  58.10    1282      2  58.1000
2007-04-30 02:28:00     2  58.10  58.10  58.10  58.10   20000      1  58.1000
2007-04-30 02:29:00     2  58.10  58.10  58.10  58.10    5000      1  58.1000
2007-04-30 02:30:00     2  58.05  58.05  58.05  58.05    2000      1  58.0500
2007-04-30 02:31:00     2  58.05  58.05  58.05  58.05   12000      1  58.0500
2007-04-30 02:32:00     2  58.05  58.05  58.05  58.05    3500      2  58.0500
2007-04-30 02:33:00     2  58.10  58.10  58.10  58.10    1000      1  58.1000
2007-04-30 02:38:00     2  58.10  58.10  58.10  58.10    8000      2  58.1000
2007-04-30 02:40:00     2  58.10  58.10  58.05  58.10   82000      3  58.0988
2007-04-30 02:41:00     2  58.10  58.10  58.10  58.10    5000      4  58.1000
2007-04-30 02:42:00     2  58.10  58.10  58.05  58.05   10500      3  58.0833
2007-04-30 02:43:00     2  58.05  58.05  58.00  58.00   25500      9  58.0245
2007-04-30 02:44:00     2  58.00  58.05  58.00  58.00   21500      4  58.0012
2007-04-30 02:45:00     2  58.00  58.00  57.80  57.80   74500      9  57.8916
2007-04-30 02:46:00     2  57.80  57.80  57.40  57.40   54500     16  57.6353
...                   ...    ...    ...    ...    ...     ...    ...      ...
2018-07-31 07:31:00     2  88.85  88.85  88.80  88.85    3000      4  88.8417
2018-07-31 07:32:00     2  88.85  88.90  88.80  88.90   25500     29  88.8569
2018-07-31 07:33:00     2  88.90  88.90  88.90  88.90    2500      3  88.9000
2018-07-31 07:34:00     2  88.90  88.90  88.90  88.90     500      1  88.9000
2018-07-31 07:35:00     2  88.90  88.90  88.85  88.85    5500      7  88.8864
2018-07-31 07:36:00     2  88.90  88.90  88.90  88.90    2500      3  88.9000
2018-07-31 07:37:00     2  88.90  88.90  88.90  88.90    1500      3  88.9000
2018-07-31 07:38:00     2  88.90  88.90  88.85  88.90    4500      7  88.8889
2018-07-31 07:39:00     2  88.85  89.00  88.85  89.00  171000     40  88.9180
2018-07-31 07:40:00     2  89.00  89.00  88.95  89.00   10500      6  88.9619
2018-07-31 07:41:00     2  89.00  89.00  88.95  89.00    3500      5  88.9929
2018-07-31 07:42:00     2  89.00  89.00  89.00  89.00   10000      5  89.0000
2018-07-31 07:43:00     2  89.00  89.00  88.95  89.00    2000      4  88.9875
2018-07-31 07:44:00     2  88.95  89.00  88.95  89.00  139500     65  88.9914
2018-07-31 07:45:00     2  89.00  89.20  89.00  89.20   88000     45  89.0889
2018-07-31 07:46:00     2  89.20  89.20  89.20  89.20    8500      6  89.2000
2018-07-31 07:47:00     2  89.20  89.25  89.20  89.25    9000     10  89.2028
2018-07-31 07:48:00     2  89.20  89.20  89.15  89.20   30500     19  89.1836
2018-07-31 07:49:00     2  89.25  89.25  89.25  89.25   11000     11  89.2500
2018-07-31 07:50:00     2  89.25  89.30  89.25  89.30   11000     15  89.2909
2018-07-31 07:51:00     2  89.30  89.40  89.30  89.40  121000     54  89.3465
2018-07-31 07:52:00     2  89.40  89.40  89.35  89.40   23000     26  89.3870
2018-07-31 07:53:00     2  89.40  89.45  89.40  89.45  102500     45  89.4110
2018-07-31 07:54:00     2  89.45  89.45  89.45  89.45    3500      7  89.4500
2018-07-31 07:55:00     2  89.45  89.50  89.45  89.50   19000     23  89.4724
2018-07-31 07:56:00     2  89.50  89.50  89.35  89.50  156500     48  89.4534
2018-07-31 07:57:00     2  89.50  89.50  89.40  89.40    4500      7  89.4389
2018-07-31 07:58:00     2  89.45  89.50  89.45  89.50   15500     13  89.4677
2018-07-31 07:59:00     2  89.45  89.70  89.45  89.70  161000    100  89.5789
2018-07-31 08:08:00     2  89.65  89.65  89.65  89.65  901000    177  89.6500

[654526 rows x 8 columns]

In [149]:
day_SEHK_2_df = SEHK_2_df.resample('B').last()
day_SEHK_2_df

            Name   Open   High    Low  Close     Volume  Count     VWAP
Date
2007-04-30   2.0  57.50  57.50  57.30  57.35    79000.0   34.0  57.4120
2007-05-01   NaN    NaN    NaN    NaN    NaN        NaN    NaN      NaN
2007-05-02   2.0  58.75  58.75  58.45  58.55   113500.0   28.0  58.6308
2007-05-03   2.0  59.05  59.05  59.05  59.05     3500.0    3.0  59.0500
2007-05-04   2.0  58.70  58.70  58.45  58.45    50500.0   18.0  58.5668
2007-05-07   2.0  58.10  58.10  58.05  58.10   125500.0   17.0  58.0580
2007-05-08   2.0  57.20  57.30  57.10  57.30   183000.0   29.0  57.2123
2007-05-09   2.0  57.75  58.00  57.75  58.00    49500.0   17.0  57.9288
2007-05-10   2.0  57.25  57.45  57.25  57.45    76500.0   15.0  57.3915
2007-05-11   2.0  57.05  57.10  57.05  57.10    93000.0    9.0  57.0847
2007-05-14   2.0  56.80  56.85  56.80  56.85    71000.0   19.0  56.8218
2007-05-15   2.0  57.15  57.20  56.90  57.20    37000.0   24.0  57.1480
2007-05-16   2.0  57.00  57.15  56.90  56.90    25500.0   10.0  57.0039
2007-05-17   2.0  56.85  57.10  56.85  57.10   146500.0   14.0  56.9657
2007-05-18   2.0  56.70  56.80  56.70  56.80     6500.0    4.0  56.7615
2007-05-21   2.0  56.50  56.50  56.40  56.40   147000.0   15.0  56.4182
2007-05-22   2.0  55.45  55.50  55.40  55.45    73500.0   21.0  55.4381
2007-05-23   2.0  55.05  55.10  55.00  55.05   206500.0   22.0  55.0150
2007-05-24   NaN    NaN    NaN    NaN    NaN        NaN    NaN      NaN
2007-05-25   2.0  54.60  54.60  54.50  54.55    57500.0   14.0  54.5491
2007-05-28   2.0  54.75  54.75  54.70  54.70    65000.0   13.0  54.7069
2007-05-29   2.0  54.65  54.65  54.60  54.65   161500.0   13.0  54.6053
2007-05-30   2.0  54.90  54.90  54.75  54.80   181000.0   35.0  54.7775
2007-05-31   2.0  55.10  55.15  55.00  55.05  3734500.0   75.0  55.0278
2007-06-01   2.0  55.45  55.45  55.05  55.05   142500.0   23.0  55.3068
2007-06-04   2.0  54.80  54.85  54.75  54.75   165500.0   15.0  54.7937
2007-06-05   2.0  54.45  54.45  54.25  54.40   246500.0   29.0  54.3165
2007-06-06   2.0  54.80  54.85  54.45  54.45    37500.0   12.0  54.7420
2007-06-07   2.0  54.70  54.70  54.30  54.30    82000.0   14.0  54.5488
2007-06-08   2.0  53.75  53.75  53.70  53.75   137000.0   16.0  53.7235
...          ...    ...    ...    ...    ...        ...    ...      ...
2018-06-20   2.0  80.70  80.75  80.70  80.75     9000.0   13.0  80.7194
2018-06-21   2.0  80.15  80.25  80.05  80.25     5000.0    7.0  80.1800
2018-06-22   2.0  80.40  80.40  80.25  80.25     4000.0    8.0  80.3625
2018-06-25   2.0  80.25  80.50  80.20  80.25    28000.0   31.0  80.2768
2018-06-26   2.0  82.75  82.75  82.65  82.75    35000.0   48.0  82.7071
2018-06-27   2.0  83.40  83.45  83.40  83.40    68000.0   64.0  83.4147
2018-06-28   2.0  84.25  84.40  84.20  84.40    20500.0   30.0  84.3439
2018-06-29   2.0  84.50  84.50  84.50  84.50   735000.0  169.0  84.5000
2018-07-02   NaN    NaN    NaN    NaN    NaN        NaN    NaN      NaN
2018-07-03   2.0  84.45  84.50  84.40  84.40    24000.0   31.0  84.4458
2018-07-04   2.0  87.30  87.35  87.30  87.35    16000.0   21.0  87.3203
2018-07-05   2.0  87.80  87.85  87.70  87.85    20500.0   25.0  87.7902
2018-07-06   2.0  88.00  88.00  87.95  88.00    13500.0   19.0  87.9852
2018-07-09   2.0  88.00  88.00  87.95  87.95    21000.0   25.0  87.9798
2018-07-10   2.0  87.55  87.55  87.45  87.45    12500.0   20.0  87.5080
2018-07-11   2.0  86.75  86.75  86.60  86.75     5500.0    9.0  86.7136
2018-07-12   2.0  87.20  87.20  87.10  87.20     9500.0   13.0  87.1842
2018-07-13   2.0  87.40  87.45  87.30  87.35    24500.0   18.0  87.3582
2018-07-16   2.0  88.40  88.40  88.35  88.40    36000.0   31.0  88.3986
2018-07-17   2.0  87.90  87.90  87.90  87.90     1500.0    2.0  87.9000
2018-07-18   2.0  88.25  88.40  88.25  88.30    38500.0   45.0  88.3247
2018-07-19   2.0  88.50  88.55  88.45  88.45    12500.0   16.0  88.4760
2018-07-20   2.0  89.35  89.35  89.20  89.30    32000.0   30.0  89.2750
2018-07-23   2.0  89.30  89.30  89.25  89.30    18000.0   29.0  89.2764
2018-07-24   2.0  88.80  89.15  88.80  88.90    20500.0   33.0  88.8854
2018-07-25   2.0  88.40  88.45  88.40  88.45    11000.0   13.0  88.4318
2018-07-26   2.0  88.50  88.50  88.45  88.45    21000.0   28.0  88.4964
2018-07-27   2.0  88.00  88.00  87.90  87.95    13000.0   18.0  87.9385
2018-07-30   2.0  88.70  88.75  88.65  88.65    25000.0   21.0  88.6880
2018-07-31   2.0  89.65  89.65  89.65  89.65   901000.0  177.0  89.6500

[2937 rows x 8 columns]

In [150]:
day_SEHK_2_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2937 entries, 2007-04-30 to 2018-07-31
Freq: B
Data columns (total 8 columns):
Name      2772 non-null float64
Open      2772 non-null float64
High      2772 non-null float64
Low       2772 non-null float64
Close     2772 non-null float64
Volume    2772 non-null float64
Count     2772 non-null float64
VWAP      2772 non-null float64
dtypes: float64(8)
memory usage: 206.5 KB

In [151]:
day_SEHK_2_df.dropna(inplace=True)

In [152]:
day_SEHK_2_df

            Name   Open   High    Low  Close     Volume  Count     VWAP
Date
2007-04-30   2.0  57.50  57.50  57.30  57.35    79000.0   34.0  57.4120
2007-05-02   2.0  58.75  58.75  58.45  58.55   113500.0   28.0  58.6308
2007-05-03   2.0  59.05  59.05  59.05  59.05     3500.0    3.0  59.0500
2007-05-04   2.0  58.70  58.70  58.45  58.45    50500.0   18.0  58.5668
2007-05-07   2.0  58.10  58.10  58.05  58.10   125500.0   17.0  58.0580
2007-05-08   2.0  57.20  57.30  57.10  57.30   183000.0   29.0  57.2123
2007-05-09   2.0  57.75  58.00  57.75  58.00    49500.0   17.0  57.9288
2007-05-10   2.0  57.25  57.45  57.25  57.45    76500.0   15.0  57.3915
2007-05-11   2.0  57.05  57.10  57.05  57.10    93000.0    9.0  57.0847
2007-05-14   2.0  56.80  56.85  56.80  56.85    71000.0   19.0  56.8218
2007-05-15   2.0  57.15  57.20  56.90  57.20    37000.0   24.0  57.1480
2007-05-16   2.0  57.00  57.15  56.90  56.90    25500.0   10.0  57.0039
2007-05-17   2.0  56.85  57.10  56.85  57.10   146500.0   14.0  56.9657
2007-05-18   2.0  56.70  56.80  56.70  56.80     6500.0    4.0  56.7615
2007-05-21   2.0  56.50  56.50  56.40  56.40   147000.0   15.0  56.4182
2007-05-22   2.0  55.45  55.50  55.40  55.45    73500.0   21.0  55.4381
2007-05-23   2.0  55.05  55.10  55.00  55.05   206500.0   22.0  55.0150
2007-05-25   2.0  54.60  54.60  54.50  54.55    57500.0   14.0  54.5491
2007-05-28   2.0  54.75  54.75  54.70  54.70    65000.0   13.0  54.7069
2007-05-29   2.0  54.65  54.65  54.60  54.65   161500.0   13.0  54.6053
2007-05-30   2.0  54.90  54.90  54.75  54.80   181000.0   35.0  54.7775
2007-05-31   2.0  55.10  55.15  55.00  55.05  3734500.0   75.0  55.0278
2007-06-01   2.0  55.45  55.45  55.05  55.05   142500.0   23.0  55.3068
2007-06-04   2.0  54.80  54.85  54.75  54.75   165500.0   15.0  54.7937
2007-06-05   2.0  54.45  54.45  54.25  54.40   246500.0   29.0  54.3165
2007-06-06   2.0  54.80  54.85  54.45  54.45    37500.0   12.0  54.7420
2007-06-07   2.0  54.70  54.70  54.30  54.30    82000.0   14.0  54.5488
2007-06-08   2.0  53.75  53.75  53.70  53.75   137000.0   16.0  53.7235
2007-06-11   2.0  54.00  54.25  53.85  54.00   149500.0   18.0  54.1189
2007-06-12   2.0  53.50  53.60  53.30  53.55    79500.0   15.0  53.4821
...          ...    ...    ...    ...    ...        ...    ...      ...
2018-06-19   2.0  80.15  80.20  80.10  80.10    26000.0   30.0  80.1702
2018-06-20   2.0  80.70  80.75  80.70  80.75     9000.0   13.0  80.7194
2018-06-21   2.0  80.15  80.25  80.05  80.25     5000.0    7.0  80.1800
2018-06-22   2.0  80.40  80.40  80.25  80.25     4000.0    8.0  80.3625
2018-06-25   2.0  80.25  80.50  80.20  80.25    28000.0   31.0  80.2768
2018-06-26   2.0  82.75  82.75  82.65  82.75    35000.0   48.0  82.7071
2018-06-27   2.0  83.40  83.45  83.40  83.40    68000.0   64.0  83.4147
2018-06-28   2.0  84.25  84.40  84.20  84.40    20500.0   30.0  84.3439
2018-06-29   2.0  84.50  84.50  84.50  84.50   735000.0  169.0  84.5000
2018-07-03   2.0  84.45  84.50  84.40  84.40    24000.0   31.0  84.4458
2018-07-04   2.0  87.30  87.35  87.30  87.35    16000.0   21.0  87.3203
2018-07-05   2.0  87.80  87.85  87.70  87.85    20500.0   25.0  87.7902
2018-07-06   2.0  88.00  88.00  87.95  88.00    13500.0   19.0  87.9852
2018-07-09   2.0  88.00  88.00  87.95  87.95    21000.0   25.0  87.9798
2018-07-10   2.0  87.55  87.55  87.45  87.45    12500.0   20.0  87.5080
2018-07-11   2.0  86.75  86.75  86.60  86.75     5500.0    9.0  86.7136
2018-07-12   2.0  87.20  87.20  87.10  87.20     9500.0   13.0  87.1842
2018-07-13   2.0  87.40  87.45  87.30  87.35    24500.0   18.0  87.3582
2018-07-16   2.0  88.40  88.40  88.35  88.40    36000.0   31.0  88.3986
2018-07-17   2.0  87.90  87.90  87.90  87.90     1500.0    2.0  87.9000
2018-07-18   2.0  88.25  88.40  88.25  88.30    38500.0   45.0  88.3247
2018-07-19   2.0  88.50  88.55  88.45  88.45    12500.0   16.0  88.4760
2018-07-20   2.0  89.35  89.35  89.20  89.30    32000.0   30.0  89.2750
2018-07-23   2.0  89.30  89.30  89.25  89.30    18000.0   29.0  89.2764
2018-07-24   2.0  88.80  89.15  88.80  88.90    20500.0   33.0  88.8854
2018-07-25   2.0  88.40  88.45  88.40  88.45    11000.0   13.0  88.4318
2018-07-26   2.0  88.50  88.50  88.45  88.45    21000.0   28.0  88.4964
2018-07-27   2.0  88.00  88.00  87.90  87.95    13000.0   18.0  87.9385
2018-07-30   2.0  88.70  88.75  88.65  88.65    25000.0   21.0  88.6880
2018-07-31   2.0  89.65  89.65  89.65  89.65   901000.0  177.0  89.6500

[2772 rows x 8 columns]

In [153]:
# Compute daily return
day_SEHK_2_df['Return'] = day_SEHK_2_df['Close'][1:].values / day_SEHK_2_df['Close'][:-1] - 1

In [154]:
# Fill missing daily return value with previous return
day_SEHK_2_df.fillna(day_SEHK_2_df['Return'].mean(), inplace=True)

In [155]:
day_SEHK_2_df

,Name,Open,High,Low,Close,Volume,Count,VWAP,Return
Date,,,,,,,,,
2007-04-30,2.0,57.50,57.50,57.30,57.35,79000.0,34.0,57.4120,0.020924
2007-05-02,2.0,58.75,58.75,58.45,58.55,113500.0,28.0,58.6308,0.008540
2007-05-03,2.0,59.05,59.05,59.05,59.05,3500.0,3.0,59.0500,-0.010161
2007-05-04,2.0,58.70,58.70,58.45,58.45,50500.0,18.0,58.5668,-0.005988
2007-05-07,2.0,58.10,58.10,58.05,58.10,125500.0,17.0,58.0580,-0.013769
2007-05-08,2.0,57.20,57.30,57.10,57.30,183000.0,29.0,57.2123,0.012216
2007-05-09,2.0,57.75,58.00,57.75,58.00,49500.0,17.0,57.9288,-0.009483
2007-05-10,2.0,57.25,57.45,57.25,57.45,76500.0,15.0,57.3915,-0.006092
2007-05-11,2.0,57.05,57.10,57.05,57.10,93000.0,9.0,57.0847,-0.004378
2007-05-14,2.0,56.80,56.85,56.80,56.85,71000.0,19.0,56.8218,0.006157
2007-05-15,2.0,57.15,57.20,56.90,57.20,37000.0,24.0,57.1480,-0.005245
2007-05-16,2.0,57.00,57.15,56.90,56.90,25500.0,10.0,57.0039,0.003515
2007-05-17,2.0,56.85,57.10,56.85,57.10,146500.0,14.0,56.9657,-0.005254
2007-05-18,2.0,56.70,56.80,56.70,56.80,6500.0,4.0,56.7615,-0.007042
2007-05-21,2.0,56.50,56.50,56.40,56.40,147000.0,15.0,56.4182,-0.016844
2007-05-22,2.0,55.45,55.50,55.40,55.45,73500.0,21.0,55.4381,-0.007214
2007-05-23,2.0,55.05,55.10,55.00,55.05,206500.0,22.0,55.0150,-0.009083
2007-05-25,2.0,54.60,54.60,54.50,54.55,57500.0,14.0,54.5491,0.002750
2007-05-28,2.0,54.75,54.75,54.70,54.70,65000.0,13.0,54.7069,-0.000914
2007-05-29,2.0,54.65,54.65,54.60,54.65,161500.0,13.0,54.6053,0.002745
2007-05-30,2.0,54.90,54.90,54.75,54.80,181000.0,35.0,54.7775,0.004562
2007-05-31,2.0,55.10,55.15,55.00,55.05,3734500.0,75.0,55.0278,0.000000
2007-06-01,2.0,55.45,55.45,55.05,55.05,142500.0,23.0,55.3068,-0.005450
2007-06-04,2.0,54.80,54.85,54.75,54.75,165500.0,15.0,54.7937,-0.006393
2007-06-05,2.0,54.45,54.45,54.25,54.40,246500.0,29.0,54.3165,0.000919
2007-06-06,2.0,54.80,54.85,54.45,54.45,37500.0,12.0,54.7420,-0.002755
2007-06-07,2.0,54.70,54.70,54.30,54.30,82000.0,14.0,54.5488,-0.010129
2007-06-08,2.0,53.75,53.75,53.70,53.75,137000.0,16.0,53.7235,0.004651
2007-06-11,2.0,54.00,54.25,53.85,54.00,149500.0,18.0,54.1189,-0.008333
2007-06-12,2.0,53.50,53.60,53.30,53.55,79500.0,15.0,53.4821,-0.000934
...,...,...,...,...,...,...,...,...,...
2018-06-19,2.0,80.15,80.20,80.10,80.10,26000.0,30.0,80.1702,0.008115
2018-06-20,2.0,80.70,80.75,80.70,80.75,9000.0,13.0,80.7194,-0.006192
2018-06-21,2.0,80.15,80.25,80.05,80.25,5000.0,7.0,80.1800,0.000000
2018-06-22,2.0,80.40,80.40,80.25,80.25,4000.0,8.0,80.3625,0.000000
2018-06-25,2.0,80.25,80.50,80.20,80.25,28000.0,31.0,80.2768,0.031153
2018-06-26,2.0,82.75,82.75,82.65,82.75,35000.0,48.0,82.7071,0.007855
2018-06-27,2.0,83.40,83.45,83.40,83.40,68000.0,64.0,83.4147,0.011990
2018-06-28,2.0,84.25,84.40,84.20,84.40,20500.0,30.0,84.3439,0.001185
2018-06-29,2.0,84.50,84.50,84.50,84.50,735000.0,169.0,84.5000,-0.001183
2018-07-03,2.0,84.45,84.50,84.40,84.40,24000.0,31.0,84.4458,0.034953
2018-07-04,2.0,87.30,87.35,87.30,87.35,16000.0,21.0,87.3203,0.005724
2018-07-05,2.0,87.80,87.85,87.70,87.85,20500.0,25.0,87.7902,0.001707
2018-07-06,2.0,88.00,88.00,87.95,88.00,13500.0,19.0,87.9852,-0.000568
2018-07-09,2.0,88.00,88.00,87.95,87.95,21000.0,25.0,87.9798,-0.005685
2018-07-10,2.0,87.55,87.55,87.45,87.45,12500.0,20.0,87.5080,-0.008005
2018-07-11,2.0,86.75,86.75,86.60,86.75,5500.0,9.0,86.7136,0.005187
2018-07-12,2.0,87.20,87.20,87.10,87.20,9500.0,13.0,87.1842,0.001720
2018-07-13,2.0,87.40,87.45,87.30,87.35,24500.0,18.0,87.3582,0.012021
2018-07-16,2.0,88.40,88.40,88.35,88.40,36000.0,31.0,88.3986,-0.005656
2018-07-17,2.0,87.90,87.90,87.90,87.90,1500.0,2.0,87.9000,0.004551
2018-07-18,2.0,88.25,88.40,88.25,88.30,38500.0,45.0,88.3247,0.001699
2018-07-19,2.0,88.50,88.55,88.45,88.45,12500.0,16.0,88.4760,0.009610
2018-07-20,2.0,89.35,89.35,89.20,89.30,32000.0,30.0,89.2750,0.000000
2018-07-23,2.0,89.30,89.30,89.25,89.30,18000.0,29.0,89.2764,-0.004479
2018-07-24,2.0,88.80,89.15,88.80,88.90,20500.0,33.0,88.8854,-0.005062
2018-07-25,2.0,88.40,88.45,88.40,88.45,11000.0,13.0,88.4318,0.000000
2018-07-26,2.0,88.50,88.50,88.45,88.45,21000.0,28.0,88.4964,-0.005653
2018-07-27,2.0,88.00,88.00,87.90,87.95,13000.0,18.0,87.9385,0.007959
2018-07-30,2.0,88.70,88.75,88.65,88.65,25000.0,21.0,88.6880,0.011280
2018-07-31,2.0,89.65,89.65,89.65,89.65,901000.0,177.0,89.6500,0.000222

In [156]:
# Compute 25-day volatility

day_SEHK_2_df['Volatility'] = day_SEHK_2_df['Return'].rolling(25).std()
day_SEHK_2_df.fillna(day_SEHK_2_df['Volatility'].mean(), inplace=True)

In [157]:
day_SEHK_2_df

,Name,Open,High,Low,Close,Volume,Count,VWAP,Return,Volatility
Date,,,,,,,,,,
2007-04-30,2.0,57.50,57.50,57.30,57.35,79000.0,34.0,57.4120,0.020924,0.009436
2007-05-02,2.0,58.75,58.75,58.45,58.55,113500.0,28.0,58.6308,0.008540,0.009436
2007-05-03,2.0,59.05,59.05,59.05,59.05,3500.0,3.0,59.0500,-0.010161,0.009436
2007-05-04,2.0,58.70,58.70,58.45,58.45,50500.0,18.0,58.5668,-0.005988,0.009436
2007-05-07,2.0,58.10,58.10,58.05,58.10,125500.0,17.0,58.0580,-0.013769,0.009436
2007-05-08,2.0,57.20,57.30,57.10,57.30,183000.0,29.0,57.2123,0.012216,0.009436
2007-05-09,2.0,57.75,58.00,57.75,58.00,49500.0,17.0,57.9288,-0.009483,0.009436
2007-05-10,2.0,57.25,57.45,57.25,57.45,76500.0,15.0,57.3915,-0.006092,0.009436
2007-05-11,2.0,57.05,57.10,57.05,57.10,93000.0,9.0,57.0847,-0.004378,0.009436
2007-05-14,2.0,56.80,56.85,56.80,56.85,71000.0,19.0,56.8218,0.006157,0.009436
2007-05-15,2.0,57.15,57.20,56.90,57.20,37000.0,24.0,57.1480,-0.005245,0.009436
2007-05-16,2.0,57.00,57.15,56.90,56.90,25500.0,10.0,57.0039,0.003515,0.009436
2007-05-17,2.0,56.85,57.10,56.85,57.10,146500.0,14.0,56.9657,-0.005254,0.009436
2007-05-18,2.0,56.70,56.80,56.70,56.80,6500.0,4.0,56.7615,-0.007042,0.009436
2007-05-21,2.0,56.50,56.50,56.40,56.40,147000.0,15.0,56.4182,-0.016844,0.009436
2007-05-22,2.0,55.45,55.50,55.40,55.45,73500.0,21.0,55.4381,-0.007214,0.009436
2007-05-23,2.0,55.05,55.10,55.00,55.05,206500.0,22.0,55.0150,-0.009083,0.009436
2007-05-25,2.0,54.60,54.60,54.50,54.55,57500.0,14.0,54.5491,0.002750,0.009436
2007-05-28,2.0,54.75,54.75,54.70,54.70,65000.0,13.0,54.7069,-0.000914,0.009436
2007-05-29,2.0,54.65,54.65,54.60,54.65,161500.0,13.0,54.6053,0.002745,0.009436
2007-05-30,2.0,54.90,54.90,54.75,54.80,181000.0,35.0,54.7775,0.004562,0.009436
2007-05-31,2.0,55.10,55.15,55.00,55.05,3734500.0,75.0,55.0278,0.000000,0.009436
2007-06-01,2.0,55.45,55.45,55.05,55.05,142500.0,23.0,55.3068,-0.005450,0.009436
2007-06-04,2.0,54.80,54.85,54.75,54.75,165500.0,15.0,54.7937,-0.006393,0.009436
2007-06-05,2.0,54.45,54.45,54.25,54.40,246500.0,29.0,54.3165,0.000919,0.008447
2007-06-06,2.0,54.80,54.85,54.45,54.45,37500.0,12.0,54.7420,-0.002755,0.006961
2007-06-07,2.0,54.70,54.70,54.30,54.30,82000.0,14.0,54.5488,-0.010129,0.006669
2007-06-08,2.0,53.75,53.75,53.70,53.75,137000.0,16.0,53.7235,0.004651,0.006731
2007-06-11,2.0,54.00,54.25,53.85,54.00,149500.0,18.0,54.1189,-0.008333,0.006789
2007-06-12,2.0,53.50,53.60,53.30,53.55,79500.0,15.0,53.4821,-0.000934,0.006435
...,...,...,...,...,...,...,...,...,...,...
2018-06-19,2.0,80.15,80.20,80.10,80.10,26000.0,30.0,80.1702,0.008115,0.009413
2018-06-20,2.0,80.70,80.75,80.70,80.75,9000.0,13.0,80.7194,-0.006192,0.008983
2018-06-21,2.0,80.15,80.25,80.05,80.25,5000.0,7.0,80.1800,0.000000,0.008782
2018-06-22,2.0,80.40,80.40,80.25,80.25,4000.0,8.0,80.3625,0.000000,0.008770
2018-06-25,2.0,80.25,80.50,80.20,80.25,28000.0,31.0,80.2768,0.031153,0.010753
2018-06-26,2.0,82.75,82.75,82.65,82.75,35000.0,48.0,82.7071,0.007855,0.009861
2018-06-27,2.0,83.40,83.45,83.40,83.40,68000.0,64.0,83.4147,0.011990,0.009796
2018-06-28,2.0,84.25,84.40,84.20,84.40,20500.0,30.0,84.3439,0.001185,0.009530
2018-06-29,2.0,84.50,84.50,84.50,84.50,735000.0,169.0,84.5000,-0.001183,0.009491
2018-07-03,2.0,84.45,84.50,84.40,84.40,24000.0,31.0,84.4458,0.034953,0.011534
2018-07-04,2.0,87.30,87.35,87.30,87.35,16000.0,21.0,87.3203,0.005724,0.011349
2018-07-05,2.0,87.80,87.85,87.70,87.85,20500.0,25.0,87.7902,0.001707,0.011320
2018-07-06,2.0,88.00,88.00,87.95,88.00,13500.0,19.0,87.9852,-0.000568,0.011281
2018-07-09,2.0,88.00,88.00,87.95,87.95,21000.0,25.0,87.9798,-0.005685,0.011065
2018-07-10,2.0,87.55,87.55,87.45,87.45,12500.0,20.0,87.5080,-0.008005,0.011218
2018-07-11,2.0,86.75,86.75,86.60,86.75,5500.0,9.0,86.7136,0.005187,0.011223
2018-07-12,2.0,87.20,87.20,87.10,87.20,9500.0,13.0,87.1842,0.001720,0.011179
2018-07-13,2.0,87.40,87.45,87.30,87.35,24500.0,18.0,87.3582,0.012021,0.011172
2018-07-16,2.0,88.40,88.40,88.35,88.40,36000.0,31.0,88.3986,-0.005656,0.010857
2018-07-17,2.0,87.90,87.90,87.90,87.90,1500.0,2.0,87.9000,0.004551,0.010827
2018-07-18,2.0,88.25,88.40,88.25,88.30,38500.0,45.0,88.3247,0.001699,0.010824
2018-07-19,2.0,88.50,88.55,88.45,88.45,12500.0,16.0,88.4760,0.009610,0.010802
2018-07-20,2.0,89.35,89.35,89.20,89.30,32000.0,30.0,89.2750,0.000000,0.010684
2018-07-23,2.0,89.30,89.30,89.25,89.30,18000.0,29.0,89.2764,-0.004479,0.010768
2018-07-24,2.0,88.80,89.15,88.80,88.90,20500.0,33.0,88.8854,-0.005062,0.010408
2018-07-25,2.0,88.40,88.45,88.40,88.45,11000.0,13.0,88.4318,0.000000,0.010402
2018-07-26,2.0,88.50,88.50,88.45,88.45,21000.0,28.0,88.4964,-0.005653,0.010381
2018-07-27,2.0,88.00,88.00,87.90,87.95,13000.0,18.0,87.9385,0.007959,0.010384
2018-07-30,2.0,88.70,88.75,88.65,88.65,25000.0,21.0,88.6880,0.011280,0.010446
2018-07-31,2.0,89.65,89.65,89.65,89.65,901000.0,177.0,89.6500,0.000222,0.008870

In [158]:
day_SEHK_2_df['Date_key'] = day_SEHK_2_df.index.date
SEHK_2_df['Date_key'] = SEHK_2_df.index.date

In [159]:
SEHK_2_df['Volatility'] = day_SEHK_2_df['Volatility']
SEHK_2_df.fillna(SEHK_2_df['Volatility'].mean(), inplace=True)

In [160]:
day_SEHK_2_df.set_index('Date_key', inplace=True)
day_SEHK_2_df

,Name,Open,High,Low,Close,Volume,Count,VWAP,Return,Volatility
Date_key,,,,,,,,,,
2007-04-30,2.0,57.50,57.50,57.30,57.35,79000.0,34.0,57.4120,0.020924,0.009436
2007-05-02,2.0,58.75,58.75,58.45,58.55,113500.0,28.0,58.6308,0.008540,0.009436
2007-05-03,2.0,59.05,59.05,59.05,59.05,3500.0,3.0,59.0500,-0.010161,0.009436
2007-05-04,2.0,58.70,58.70,58.45,58.45,50500.0,18.0,58.5668,-0.005988,0.009436
2007-05-07,2.0,58.10,58.10,58.05,58.10,125500.0,17.0,58.0580,-0.013769,0.009436
2007-05-08,2.0,57.20,57.30,57.10,57.30,183000.0,29.0,57.2123,0.012216,0.009436
2007-05-09,2.0,57.75,58.00,57.75,58.00,49500.0,17.0,57.9288,-0.009483,0.009436
2007-05-10,2.0,57.25,57.45,57.25,57.45,76500.0,15.0,57.3915,-0.006092,0.009436
2007-05-11,2.0,57.05,57.10,57.05,57.10,93000.0,9.0,57.0847,-0.004378,0.009436
2007-05-14,2.0,56.80,56.85,56.80,56.85,71000.0,19.0,56.8218,0.006157,0.009436
2007-05-15,2.0,57.15,57.20,56.90,57.20,37000.0,24.0,57.1480,-0.005245,0.009436
2007-05-16,2.0,57.00,57.15,56.90,56.90,25500.0,10.0,57.0039,0.003515,0.009436
2007-05-17,2.0,56.85,57.10,56.85,57.10,146500.0,14.0,56.9657,-0.005254,0.009436
2007-05-18,2.0,56.70,56.80,56.70,56.80,6500.0,4.0,56.7615,-0.007042,0.009436
2007-05-21,2.0,56.50,56.50,56.40,56.40,147000.0,15.0,56.4182,-0.016844,0.009436
2007-05-22,2.0,55.45,55.50,55.40,55.45,73500.0,21.0,55.4381,-0.007214,0.009436
2007-05-23,2.0,55.05,55.10,55.00,55.05,206500.0,22.0,55.0150,-0.009083,0.009436
2007-05-25,2.0,54.60,54.60,54.50,54.55,57500.0,14.0,54.5491,0.002750,0.009436
2007-05-28,2.0,54.75,54.75,54.70,54.70,65000.0,13.0,54.7069,-0.000914,0.009436
2007-05-29,2.0,54.65,54.65,54.60,54.65,161500.0,13.0,54.6053,0.002745,0.009436
2007-05-30,2.0,54.90,54.90,54.75,54.80,181000.0,35.0,54.7775,0.004562,0.009436
2007-05-31,2.0,55.10,55.15,55.00,55.05,3734500.0,75.0,55.0278,0.000000,0.009436
2007-06-01,2.0,55.45,55.45,55.05,55.05,142500.0,23.0,55.3068,-0.005450,0.009436
2007-06-04,2.0,54.80,54.85,54.75,54.75,165500.0,15.0,54.7937,-0.006393,0.009436
2007-06-05,2.0,54.45,54.45,54.25,54.40,246500.0,29.0,54.3165,0.000919,0.008447
2007-06-06,2.0,54.80,54.85,54.45,54.45,37500.0,12.0,54.7420,-0.002755,0.006961
2007-06-07,2.0,54.70,54.70,54.30,54.30,82000.0,14.0,54.5488,-0.010129,0.006669
2007-06-08,2.0,53.75,53.75,53.70,53.75,137000.0,16.0,53.7235,0.004651,0.006731
2007-06-11,2.0,54.00,54.25,53.85,54.00,149500.0,18.0,54.1189,-0.008333,0.006789
2007-06-12,2.0,53.50,53.60,53.30,53.55,79500.0,15.0,53.4821,-0.000934,0.006435
...,...,...,...,...,...,...,...,...,...,...
2018-06-19,2.0,80.15,80.20,80.10,80.10,26000.0,30.0,80.1702,0.008115,0.009413
2018-06-20,2.0,80.70,80.75,80.70,80.75,9000.0,13.0,80.7194,-0.006192,0.008983
2018-06-21,2.0,80.15,80.25,80.05,80.25,5000.0,7.0,80.1800,0.000000,0.008782
2018-06-22,2.0,80.40,80.40,80.25,80.25,4000.0,8.0,80.3625,0.000000,0.008770
2018-06-25,2.0,80.25,80.50,80.20,80.25,28000.0,31.0,80.2768,0.031153,0.010753
2018-06-26,2.0,82.75,82.75,82.65,82.75,35000.0,48.0,82.7071,0.007855,0.009861
2018-06-27,2.0,83.40,83.45,83.40,83.40,68000.0,64.0,83.4147,0.011990,0.009796
2018-06-28,2.0,84.25,84.40,84.20,84.40,20500.0,30.0,84.3439,0.001185,0.009530
2018-06-29,2.0,84.50,84.50,84.50,84.50,735000.0,169.0,84.5000,-0.001183,0.009491
2018-07-03,2.0,84.45,84.50,84.40,84.40,24000.0,31.0,84.4458,0.034953,0.011534
2018-07-04,2.0,87.30,87.35,87.30,87.35,16000.0,21.0,87.3203,0.005724,0.011349
2018-07-05,2.0,87.80,87.85,87.70,87.85,20500.0,25.0,87.7902,0.001707,0.011320
2018-07-06,2.0,88.00,88.00,87.95,88.00,13500.0,19.0,87.9852,-0.000568,0.011281
2018-07-09,2.0,88.00,88.00,87.95,87.95,21000.0,25.0,87.9798,-0.005685,0.011065
2018-07-10,2.0,87.55,87.55,87.45,87.45,12500.0,20.0,87.5080,-0.008005,0.011218
2018-07-11,2.0,86.75,86.75,86.60,86.75,5500.0,9.0,86.7136,0.005187,0.011223
2018-07-12,2.0,87.20,87.20,87.10,87.20,9500.0,13.0,87.1842,0.001720,0.011179
2018-07-13,2.0,87.40,87.45,87.30,87.35,24500.0,18.0,87.3582,0.012021,0.011172
2018-07-16,2.0,88.40,88.40,88.35,88.40,36000.0,31.0,88.3986,-0.005656,0.010857
2018-07-17,2.0,87.90,87.90,87.90,87.90,1500.0,2.0,87.9000,0.004551,0.010827
2018-07-18,2.0,88.25,88.40,88.25,88.30,38500.0,45.0,88.3247,0.001699,0.010824
2018-07-19,2.0,88.50,88.55,88.45,88.45,12500.0,16.0,88.4760,0.009610,0.010802
2018-07-20,2.0,89.35,89.35,89.20,89.30,32000.0,30.0,89.2750,0.000000,0.010684
2018-07-23,2.0,89.30,89.30,89.25,89.30,18000.0,29.0,89.2764,-0.004479,0.010768
2018-07-24,2.0,88.80,89.15,88.80,88.90,20500.0,33.0,88.8854,-0.005062,0.010408
2018-07-25,2.0,88.40,88.45,88.40,88.45,11000.0,13.0,88.4318,0.000000,0.010402
2018-07-26,2.0,88.50,88.50,88.45,88.45,21000.0,28.0,88.4964,-0.005653,0.010381
2018-07-27,2.0,88.00,88.00,87.90,87.95,13000.0,18.0,87.9385,0.007959,0.010384
2018-07-30,2.0,88.70,88.75,88.65,88.65,25000.0,21.0,88.6880,0.011280,0.010446
2018-07-31,2.0,89.65,89.65,89.65,89.65,901000.0,177.0,89.6500,0.000222,0.008870

In [161]:
SEHK_2_df.set_index('Date_key', inplace=True)
SEHK_2_df

,Name,Open,High,Low,Close,Volume,Count,VWAP,Volatility
Date_key,,,,,,,,,
2007-04-30,2,59.05,59.05,58.50,58.50,5000,6,58.6550,NaN
2007-04-30,2,58.50,58.50,58.50,58.50,1000,1,58.5000,NaN
2007-04-30,2,58.35,58.35,58.35,58.35,2000,1,58.3500,NaN
2007-04-30,2,58.40,58.40,58.40,58.40,25000,1,58.4000,NaN
2007-04-30,2,58.35,58.40,58.35,58.40,3000,2,58.3667,NaN
2007-04-30,2,58.40,58.40,58.40,58.40,15000,1,58.4000,NaN
2007-04-30,2,58.35,58.35,58.35,58.35,4500,2,58.3500,NaN
2007-04-30,2,58.35,58.35,58.35,58.35,2000,1,58.3500,NaN
2007-04-30,2,58.30,58.30,58.20,58.20,6000,3,58.2667,NaN
2007-04-30,2,58.25,58.25,58.25,58.25,2500,1,58.2500,NaN
2007-04-30,2,58.20,58.20,58.10,58.10,25000,4,58.1940,NaN
2007-04-30,2,58.10,58.10,58.10,58.10,22500,3,58.1000,NaN
2007-04-30,2,58.10,58.15,58.00,58.15,110000,3,58.1032,NaN
2007-04-30,2,58.10,58.10,58.10,58.10,2000,1,58.1000,NaN
2007-04-30,2,58.10,58.10,58.00,58.00,18000,3,58.0194,NaN
2007-04-30,2,58.10,58.10,58.10,58.10,1282,2,58.1000,NaN
2007-04-30,2,58.10,58.10,58.10,58.10,20000,1,58.1000,NaN
2007-04-30,2,58.10,58.10,58.10,58.10,5000,1,58.1000,NaN
2007-04-30,2,58.05,58.05,58.05,58.05,2000,1,58.0500,NaN
2007-04-30,2,58.05,58.05,58.05,58.05,12000,1,58.0500,NaN
2007-04-30,2,58.05,58.05,58.05,58.05,3500,2,58.0500,NaN
2007-04-30,2,58.10,58.10,58.10,58.10,1000,1,58.1000,NaN
2007-04-30,2,58.10,58.10,58.10,58.10,8000,2,58.1000,NaN
2007-04-30,2,58.10,58.10,58.05,58.10,82000,3,58.0988,NaN
2007-04-30,2,58.10,58.10,58.10,58.10,5000,4,58.1000,NaN
2007-04-30,2,58.10,58.10,58.05,58.05,10500,3,58.0833,NaN
2007-04-30,2,58.05,58.05,58.00,58.00,25500,9,58.0245,NaN
2007-04-30,2,58.00,58.05,58.00,58.00,21500,4,58.0012,NaN
2007-04-30,2,58.00,58.00,57.80,57.80,74500,9,57.8916,NaN
2007-04-30,2,57.80,57.80,57.40,57.40,54500,16,57.6353,NaN
...,...,...,...,...,...,...,...,...,...
2018-07-31,2,88.85,88.85,88.80,88.85,3000,4,88.8417,NaN
2018-07-31,2,88.85,88.90,88.80,88.90,25500,29,88.8569,NaN
2018-07-31,2,88.90,88.90,88.90,88.90,2500,3,88.9000,NaN
2018-07-31,2,88.90,88.90,88.90,88.90,500,1,88.9000,NaN
2018-07-31,2,88.90,88.90,88.85,88.85,5500,7,88.8864,NaN
2018-07-31,2,88.90,88.90,88.90,88.90,2500,3,88.9000,NaN
2018-07-31,2,88.90,88.90,88.90,88.90,1500,3,88.9000,NaN
2018-07-31,2,88.90,88.90,88.85,88.90,4500,7,88.8889,NaN
2018-07-31,2,88.85,89.00,88.85,89.00,171000,40,88.9180,NaN
2018-07-31,2,89.00,89.00,88.95,89.00,10500,6,88.9619,NaN
2018-07-31,2,89.00,89.00,88.95,89.00,3500,5,88.9929,NaN
2018-07-31,2,89.00,89.00,89.00,89.00,10000,5,89.0000,NaN
2018-07-31,2,89.00,89.00,88.95,89.00,2000,4,88.9875,NaN
2018-07-31,2,88.95,89.00,88.95,89.00,139500,65,88.9914,NaN
2018-07-31,2,89.00,89.20,89.00,89.20,88000,45,89.0889,NaN
2018-07-31,2,89.20,89.20,89.20,89.20,8500,6,89.2000,NaN
2018-07-31,2,89.20,89.25,89.20,89.25,9000,10,89.2028,NaN
2018-07-31,2,89.20,89.20,89.15,89.20,30500,19,89.1836,NaN
2018-07-31,2,89.25,89.25,89.25,89.25,11000,11,89.2500,NaN
2018-07-31,2,89.25,89.30,89.25,89.30,11000,15,89.2909,NaN
2018-07-31,2,89.30,89.40,89.30,89.40,121000,54,89.3465,NaN
2018-07-31,2,89.40,89.40,89.35,89.40,23000,26,89.3870,NaN
2018-07-31,2,89.40,89.45,89.40,89.45,102500,45,89.4110,NaN
2018-07-31,2,89.45,89.45,89.45,89.45,3500,7,89.4500,NaN
2018-07-31,2,89.45,89.50,89.45,89.50,19000,23,89.4724,NaN
2018-07-31,2,89.50,89.50,89.35,89.50,156500,48,89.4534,NaN
2018-07-31,2,89.50,89.50,89.40,89.40,4500,7,89.4389,NaN
2018-07-31,2,89.45,89.50,89.45,89.50,15500,13,89.4677,NaN
2018-07-31,2,89.45,89.70,89.45,89.70,161000,100,89.5789,NaN
2018-07-31,2,89.65,89.65,89.65,89.65,901000,177,89.6500,NaN

In [162]:
# Merge 25-day Volatility to intraday dataset
SEHK_2_df['Volatility'] = day_SEHK_2_df['Volatility']
SEHK_2_df.fillna(SEHK_2_df['Volatility'].mean(), inplace=True)

In [163]:
# day_SEHK_2_df = SEHK_2_df.resample('B').last()
# day_SEHK_2_df
SEHK_2_df

,Name,Open,High,Low,Close,Volume,Count,VWAP,Volatility
Date_key,,,,,,,,,
2007-04-30,2,59.05,59.05,58.50,58.50,5000,6,58.6550,0.009436
2007-04-30,2,58.50,58.50,58.50,58.50,1000,1,58.5000,0.009436
2007-04-30,2,58.35,58.35,58.35,58.35,2000,1,58.3500,0.009436
2007-04-30,2,58.40,58.40,58.40,58.40,25000,1,58.4000,0.009436
2007-04-30,2,58.35,58.40,58.35,58.40,3000,2,58.3667,0.009436
2007-04-30,2,58.40,58.40,58.40,58.40,15000,1,58.4000,0.009436
2007-04-30,2,58.35,58.35,58.35,58.35,4500,2,58.3500,0.009436
2007-04-30,2,58.35,58.35,58.35,58.35,2000,1,58.3500,0.009436
2007-04-30,2,58.30,58.30,58.20,58.20,6000,3,58.2667,0.009436
2007-04-30,2,58.25,58.25,58.25,58.25,2500,1,58.2500,0.009436
2007-04-30,2,58.20,58.20,58.10,58.10,25000,4,58.1940,0.009436
2007-04-30,2,58.10,58.10,58.10,58.10,22500,3,58.1000,0.009436
2007-04-30,2,58.10,58.15,58.00,58.15,110000,3,58.1032,0.009436
2007-04-30,2,58.10,58.10,58.10,58.10,2000,1,58.1000,0.009436
2007-04-30,2,58.10,58.10,58.00,58.00,18000,3,58.0194,0.009436
2007-04-30,2,58.10,58.10,58.10,58.10,1282,2,58.1000,0.009436
2007-04-30,2,58.10,58.10,58.10,58.10,20000,1,58.1000,0.009436
2007-04-30,2,58.10,58.10,58.10,58.10,5000,1,58.1000,0.009436
2007-04-30,2,58.05,58.05,58.05,58.05,2000,1,58.0500,0.009436
2007-04-30,2,58.05,58.05,58.05,58.05,12000,1,58.0500,0.009436
2007-04-30,2,58.05,58.05,58.05,58.05,3500,2,58.0500,0.009436
2007-04-30,2,58.10,58.10,58.10,58.10,1000,1,58.1000,0.009436
2007-04-30,2,58.10,58.10,58.10,58.10,8000,2,58.1000,0.009436
2007-04-30,2,58.10,58.10,58.05,58.10,82000,3,58.0988,0.009436
2007-04-30,2,58.10,58.10,58.10,58.10,5000,4,58.1000,0.009436
2007-04-30,2,58.10,58.10,58.05,58.05,10500,3,58.0833,0.009436
2007-04-30,2,58.05,58.05,58.00,58.00,25500,9,58.0245,0.009436
2007-04-30,2,58.00,58.05,58.00,58.00,21500,4,58.0012,0.009436
2007-04-30,2,58.00,58.00,57.80,57.80,74500,9,57.8916,0.009436
2007-04-30,2,57.80,57.80,57.40,57.40,54500,16,57.6353,0.009436
...,...,...,...,...,...,...,...,...,...
2018-07-31,2,88.85,88.85,88.80,88.85,3000,4,88.8417,0.008870
2018-07-31,2,88.85,88.90,88.80,88.90,25500,29,88.8569,0.008870
2018-07-31,2,88.90,88.90,88.90,88.90,2500,3,88.9000,0.008870
2018-07-31,2,88.90,88.90,88.90,88.90,500,1,88.9000,0.008870
2018-07-31,2,88.90,88.90,88.85,88.85,5500,7,88.8864,0.008870
2018-07-31,2,88.90,88.90,88.90,88.90,2500,3,88.9000,0.008870
2018-07-31,2,88.90,88.90,88.90,88.90,1500,3,88.9000,0.008870
2018-07-31,2,88.90,88.90,88.85,88.90,4500,7,88.8889,0.008870
2018-07-31,2,88.85,89.00,88.85,89.00,171000,40,88.9180,0.008870
2018-07-31,2,89.00,89.00,88.95,89.00,10500,6,88.9619,0.008870
2018-07-31,2,89.00,89.00,88.95,89.00,3500,5,88.9929,0.008870
2018-07-31,2,89.00,89.00,89.00,89.00,10000,5,89.0000,0.008870
2018-07-31,2,89.00,89.00,88.95,89.00,2000,4,88.9875,0.008870
2018-07-31,2,88.95,89.00,88.95,89.00,139500,65,88.9914,0.008870
2018-07-31,2,89.00,89.20,89.00,89.20,88000,45,89.0889,0.008870
2018-07-31,2,89.20,89.20,89.20,89.20,8500,6,89.2000,0.008870
2018-07-31,2,89.20,89.25,89.20,89.25,9000,10,89.2028,0.008870
2018-07-31,2,89.20,89.20,89.15,89.20,30500,19,89.1836,0.008870
2018-07-31,2,89.25,89.25,89.25,89.25,11000,11,89.2500,0.008870
2018-07-31,2,89.25,89.30,89.25,89.30,11000,15,89.2909,0.008870
2018-07-31,2,89.30,89.40,89.30,89.40,121000,54,89.3465,0.008870
2018-07-31,2,89.40,89.40,89.35,89.40,23000,26,89.3870,0.008870
2018-07-31,2,89.40,89.45,89.40,89.45,102500,45,89.4110,0.008870
2018-07-31,2,89.45,89.45,89.45,89.45,3500,7,89.4500,0.008870
2018-07-31,2,89.45,89.50,89.45,89.50,19000,23,89.4724,0.008870
2018-07-31,2,89.50,89.50,89.35,89.50,156500,48,89.4534,0.008870
2018-07-31,2,89.50,89.50,89.40,89.40,4500,7,89.4389,0.008870
2018-07-31,2,89.45,89.50,89.45,89.50,15500,13,89.4677,0.008870
2018-07-31,2,89.45,89.70,89.45,89.70,161000,100,89.5789,0.008870
2018-07-31,2,89.65,89.65,89.65,89.65,901000,177,89.6500,0.008870

In [164]:
SEHK_2_df2 = csvdf[:'2018'].copy()
day_SEHK_2_df2 = SEHK_2_df2.resample('B').mean()
day_SEHK_2_df2.dropna(inplace=True)
# day_SEHK_2_df2
daily_average_volume = day_SEHK_2_df2['Volume']

In [165]:
day_SEHK_2_df2

,Name,Open,High,Low,Close,Volume,Count,VWAP
Date,,,,,,,,
2007-04-30,2.0,57.761834,57.776923,57.737574,57.753254,16467.408284,2.905325,57.757801
2007-05-02,2.0,58.653429,58.675714,58.629714,58.654571,12368.365714,2.765714,58.660855
2007-05-03,2.0,59.272083,59.296667,59.238611,59.272778,19152.972222,3.183333,59.283924
2007-05-04,2.0,58.948800,58.973200,58.922400,58.948800,10094.464000,2.496000,58.948195
2007-05-07,2.0,58.729878,58.746037,58.698476,58.714939,15344.042683,3.207317,58.719999
2007-05-08,2.0,57.544700,57.553917,57.521429,57.541935,19954.778802,4.497696,57.539841
2007-05-09,2.0,57.818129,57.831871,57.800000,57.815789,9855.514620,2.649123,57.819016
2007-05-10,2.0,57.586054,57.787755,57.576871,57.777551,15470.591837,2.904762,57.599676
2007-05-11,2.0,57.275146,57.291520,57.258772,57.273977,14569.204678,3.538012,57.272326
2007-05-14,2.0,57.196445,57.206635,57.180569,57.196445,25877.071090,4.094787,57.193968
2007-05-15,2.0,56.977742,57.008387,56.952581,56.986452,16223.632258,5.122581,56.982180
2007-05-16,2.0,57.087676,57.099648,57.062676,57.076056,10736.274648,2.802817,57.085521
2007-05-17,2.0,56.940000,56.946316,56.922895,56.933684,23977.731579,3.189474,56.935396
2007-05-18,2.0,56.571858,56.589071,56.549180,56.573497,12657.704918,2.770492,56.576008
2007-05-21,2.0,56.799112,56.813609,56.776627,56.797337,12001.041420,2.532544,56.801560
2007-05-22,2.0,55.749127,55.766812,55.728166,55.749563,28156.925764,5.986900,55.748665
2007-05-23,2.0,55.365728,55.376995,55.349061,55.361737,20850.661972,3.943662,55.362666
2007-05-25,2.0,54.650448,54.666143,54.614126,54.634081,16685.650224,4.304933,54.648561
2007-05-28,2.0,54.831311,54.848544,54.814320,54.833252,13783.893204,3.378641,54.835831
2007-05-29,2.0,54.730114,54.734659,54.716761,54.725852,19057.840909,2.840909,54.726410
2007-05-30,2.0,54.711374,54.726066,54.690995,54.713270,20578.241706,5.303318,54.710308
2007-05-31,2.0,55.003704,55.025694,54.987500,55.014815,81441.569444,6.750000,55.007543
2007-06-01,2.0,55.266209,55.307692,55.241209,55.281868,24812.989011,3.521978,55.283481
2007-06-04,2.0,55.091573,55.106180,55.073315,55.084270,12722.202247,2.432584,55.086474
2007-06-05,2.0,54.604497,54.624571,54.580519,54.601058,35120.190476,3.878307,54.602042
2007-06-06,2.0,54.631768,54.648343,54.612983,54.631215,13518.193370,3.055249,54.630635
2007-06-07,2.0,54.364359,54.392564,54.347949,54.379231,17433.435897,5.420513,54.367744
2007-06-08,2.0,53.706250,53.728935,53.679167,53.711574,24946.254630,7.907407,53.702945
2007-06-11,2.0,53.892564,53.920000,53.868974,53.888718,18632.410256,3.728205,53.895846
2007-06-12,2.0,53.336700,53.358621,53.311084,53.338177,11048.916256,4.891626,53.337580
...,...,...,...,...,...,...,...,...
2018-06-19,2.0,80.601290,80.627581,80.576290,80.597581,12819.354839,12.222581,80.603207
2018-06-20,2.0,80.586166,80.609881,80.569763,80.589921,6683.794466,7.015810,80.589384
2018-06-21,2.0,80.705166,80.737269,80.684133,80.709594,6287.822878,6.889299,80.706065
2018-06-22,2.0,80.204520,80.218079,80.191808,80.203390,4361.581921,3.711864,80.205705
2018-06-25,2.0,80.525283,80.548113,80.505472,80.526415,6424.528302,7.298113,80.524720
2018-06-26,2.0,81.768109,81.789423,81.748558,81.778526,16466.346154,12.785256,81.767511
2018-06-27,2.0,83.293891,83.315756,83.278135,83.297588,17485.530547,12.665595,83.296083
2018-06-28,2.0,83.416370,83.452847,83.394128,83.432206,14848.754448,12.615658,83.423063
2018-06-29,2.0,84.503311,84.521358,84.488576,84.508113,14264.900662,10.453642,84.501629
2018-07-03,2.0,83.995349,84.019186,83.981977,84.001357,12065.891473,11.240310,83.998078
2018-07-04,2.0,86.802769,86.849837,86.772313,86.816938,18338.762215,12.231270,86.805727
2018-07-05,2.0,87.289500,87.319667,87.256833,87.296000,14970.000000,12.150000,87.288304
2018-07-06,2.0,87.982000,88.006833,87.956167,87.982833,15495.000000,12.123333,87.980171
2018-07-09,2.0,88.035200,88.052800,88.016600,88.032600,12690.000000,8.412000,88.034422
2018-07-10,2.0,87.714983,87.732927,87.694425,87.710801,9719.512195,8.564460,87.712542
2018-07-11,2.0,86.706878,86.720370,86.675661,86.697090,11671.957672,7.068783,86.699605
2018-07-12,2.0,87.307583,87.319431,87.289810,87.302607,5533.175355,6.341232,87.305418
2018-07-13,2.0,87.650862,87.667672,87.633190,87.651293,5926.724138,6.698276,87.650499
2018-07-16,2.0,88.224111,88.249209,88.209289,88.235375,6648.221344,6.984190,88.226718
2018-07-17,2.0,88.182440,88.200893,88.164583,88.186012,5154.761905,5.952381,88.181361
2018-07-18,2.0,88.327966,88.348305,88.317585,88.338136,7008.474576,7.508475,88.332221
2018-07-19,2.0,88.456048,88.468347,88.439516,88.449395,7782.258065,6.213710,88.455071
2018-07-20,2.0,88.963110,88.984146,88.934604,88.966463,9239.329268,8.695122,88.959729
2018-07-23,2.0,89.254378,89.268664,89.243548,89.255760,7223.502304,5.460829,89.255312
2018-07-24,2.0,88.909752,88.930805,88.894737,88.912384,6479.876161,7.362229,88.908304
2018-07-25,2.0,88.597280,88.626778,88.576360,88.599372,7048.117155,8.092050,88.597416
2018-07-26,2.0,88.263357,88.286101,88.241877,88.264982,5350.180505,5.317690,88.260758
2018-07-27,2.0,87.913057,87.932803,87.893631,87.915924,4226.114650,5.261146,87.910881
2018-07-30,2.0,88.652165,88.666017,88.636580,88.650866,6850.649351,6.722944,88.648308
2018-07-31,2.0,88.949432,88.965152,88.936742,88.957197,11356.060606,6.405303,88.951775

In [166]:
previous_daily_average_volume = daily_average_volume.shift(1)

In [167]:
previous_daily_average_volume.fillna(previous_daily_average_volume.mean(), inplace=True)
previous_daily_average_volume

Date
2007-04-30    13117.702625
2007-05-02    16467.408284
2007-05-03    12368.365714
2007-05-04    19152.972222
2007-05-07    10094.464000
2007-05-08    15344.042683
2007-05-09    19954.778802
2007-05-10     9855.514620
2007-05-11    15470.591837
2007-05-14    14569.204678
2007-05-15    25877.071090
2007-05-16    16223.632258
2007-05-17    10736.274648
2007-05-18    23977.731579
2007-05-21    12657.704918
2007-05-22    12001.041420
2007-05-23    28156.925764
2007-05-25    20850.661972
2007-05-28    16685.650224
2007-05-29    13783.893204
2007-05-30    19057.840909
2007-05-31    20578.241706
2007-06-01    81441.569444
2007-06-04    24812.989011
2007-06-05    12722.202247
2007-06-06    35120.190476
2007-06-07    13518.193370
2007-06-08    17433.435897
2007-06-11    24946.254630
2007-06-12    18632.410256
                  ...
2018-06-19     7654.618474
2018-06-20    12819.354839
2018-06-21     6683.794466
2018-06-22     6287.822878
2018-06-25     4361.581921
2018-06-26     6424.528302
2018-06-27    16466.346154
2018-06-28    17485.530547
2018-06-29    14848.754448
2018-07-03    14264.900662
2018-07-04    12065.891473
2018-07-05    18338.762215
2018-07-06    14970.000000
2018-07-09    15495.000000
2018-07-10    12690.000000
2018-07-11     9719.512195
2018-07-12    11671.957672
2018-07-13     5533.175355
2018-07-16     5926.724138
2018-07-17     6648.221344
2018-07-18     5154.761905
2018-07-19     7008.474576
2018-07-20     7782.258065
2018-07-23     9239.329268
2018-07-24     7223.502304
2018-07-25     6479.876161
2018-07-26     7048.117155
2018-07-27     5350.180505
2018-07-30     4226.114650
2018-07-31     6850.649351
Name: Volume, Length: 2772, dtype: float64

In [168]:
daily_average_volume

Date
2007-04-30    16467.408284
2007-05-02    12368.365714
2007-05-03    19152.972222
2007-05-04    10094.464000
2007-05-07    15344.042683
2007-05-08    19954.778802
2007-05-09     9855.514620
2007-05-10    15470.591837
2007-05-11    14569.204678
2007-05-14    25877.071090
2007-05-15    16223.632258
2007-05-16    10736.274648
2007-05-17    23977.731579
2007-05-18    12657.704918
2007-05-21    12001.041420
2007-05-22    28156.925764
2007-05-23    20850.661972
2007-05-25    16685.650224
2007-05-28    13783.893204
2007-05-29    19057.840909
2007-05-30    20578.241706
2007-05-31    81441.569444
2007-06-01    24812.989011
2007-06-04    12722.202247
2007-06-05    35120.190476
2007-06-06    13518.193370
2007-06-07    17433.435897
2007-06-08    24946.254630
2007-06-11    18632.410256
2007-06-12    11048.916256
                  ...
2018-06-19    12819.354839
2018-06-20     6683.794466
2018-06-21     6287.822878
2018-06-22     4361.581921
2018-06-25     6424.528302
2018-06-26    16466.346154
2018-06-27    17485.530547
2018-06-28    14848.754448
2018-06-29    14264.900662
2018-07-03    12065.891473
2018-07-04    18338.762215
2018-07-05    14970.000000
2018-07-06    15495.000000
2018-07-09    12690.000000
2018-07-10     9719.512195
2018-07-11    11671.957672
2018-07-12     5533.175355
2018-07-13     5926.724138
2018-07-16     6648.221344
2018-07-17     5154.761905
2018-07-18     7008.474576
2018-07-19     7782.258065
2018-07-20     9239.329268
2018-07-23     7223.502304
2018-07-24     6479.876161
2018-07-25     7048.117155
2018-07-26     5350.180505
2018-07-27     4226.114650
2018-07-30     6850.649351
2018-07-31    11356.060606
Name: Volume, Length: 2772, dtype: float64

In [169]:
SEHK_2_df['Daily_Average_Volume'] = daily_average_volume.round(0).fillna(0)

In [170]:
SEHK_2_df['Previous_Daily_Average_Volume'] = previous_daily_average_volume.round(0).fillna(0)

In [171]:
SEHK_2_df['Trading Volume'] = SEHK_2_df['Volume'][:] / SEHK_2_df['Count'][:]

In [172]:
# Rounding volume
SEHK_2_df['Trading Volume'] = SEHK_2_df['Trading Volume'].round(0).fillna(0)

In [173]:
SEHK_2_df['Size'] = SEHK_2_df['Trading Volume'][:] / SEHK_2_df['Previous_Daily_Average_Volume'][:]

In [174]:
SEHK_2_df['Volatility'] = SEHK_2_df['Volatility'].round(4).fillna(0)
SEHK_2_df['Size'] = SEHK_2_df['Size'].round(4).fillna(0)

In [175]:
SEHK_2_df['POV'] = SEHK_2_df['Trading Volume'][:] / SEHK_2_df['Trading Volume'].rolling(30).sum()

In [176]:
SEHK_2_df['POV'].fillna(SEHK_2_df['POV'].mean(), inplace=True)

In [177]:
SEHK_2_df['Cost'] = (np.log(SEHK_2_df['VWAP'][:]) - (np.log((SEHK_2_df['High'][:] + SEHK_2_df['Low'][:]) / 2))).abs()*10000
SEHK_2_df['Cost'] = SEHK_2_df['Cost'].round(4)

In [178]:
SEHK_2_df

,Name,Open,High,Low,Close,Volume,Count,VWAP,Volatility,Daily_Average_Volume,Previous_Daily_Average_Volume,Trading Volume,Size,POV,Cost
Date_key,,,,,,,,,,,,,,,
2007-04-30,2,59.05,59.05,58.50,58.50,5000,6,58.6550,0.0094,16467.0,13118.0,833.0,0.0635,0.033608,20.4377
2007-04-30,2,58.50,58.50,58.50,58.50,1000,1,58.5000,0.0094,16467.0,13118.0,1000.0,0.0762,0.033608,0.0000
2007-04-30,2,58.35,58.35,58.35,58.35,2000,1,58.3500,0.0094,16467.0,13118.0,2000.0,0.1525,0.033608,0.0000
2007-04-30,2,58.40,58.40,58.40,58.40,25000,1,58.4000,0.0094,16467.0,13118.0,25000.0,1.9058,0.033608,0.0000
2007-04-30,2,58.35,58.40,58.35,58.40,3000,2,58.3667,0.0094,16467.0,13118.0,1500.0,0.1143,0.033608,1.4219
2007-04-30,2,58.40,58.40,58.40,58.40,15000,1,58.4000,0.0094,16467.0,13118.0,15000.0,1.1435,0.033608,0.0000
2007-04-30,2,58.35,58.35,58.35,58.35,4500,2,58.3500,0.0094,16467.0,13118.0,2250.0,0.1715,0.033608,0.0000
2007-04-30,2,58.35,58.35,58.35,58.35,2000,1,58.3500,0.0094,16467.0,13118.0,2000.0,0.1525,0.033608,0.0000
2007-04-30,2,58.30,58.30,58.20,58.20,6000,3,58.2667,0.0094,16467.0,13118.0,2000.0,0.1525,0.033608,2.8665
2007-04-30,2,58.25,58.25,58.25,58.25,2500,1,58.2500,0.0094,16467.0,13118.0,2500.0,0.1906,0.033608,0.0000
2007-04-30,2,58.20,58.20,58.10,58.10,25000,4,58.1940,0.0094,16467.0,13118.0,6250.0,0.4764,0.033608,7.5638
2007-04-30,2,58.10,58.10,58.10,58.10,22500,3,58.1000,0.0094,16467.0,13118.0,7500.0,0.5717,0.033608,0.0000
2007-04-30,2,58.10,58.15,58.00,58.15,110000,3,58.1032,0.0094,16467.0,13118.0,36667.0,2.7952,0.033608,4.8546
2007-04-30,2,58.10,58.10,58.10,58.10,2000,1,58.1000,0.0094,16467.0,13118.0,2000.0,0.1525,0.033608,0.0000
2007-04-30,2,58.10,58.10,58.00,58.00,18000,3,58.0194,0.0094,16467.0,13118.0,6000.0,0.4574,0.033608,5.2727
2007-04-30,2,58.10,58.10,58.10,58.10,1282,2,58.1000,0.0094,16467.0,13118.0,641.0,0.0489,0.033608,0.0000
2007-04-30,2,58.10,58.10,58.10,58.10,20000,1,58.1000,0.0094,16467.0,13118.0,20000.0,1.5246,0.033608,0.0000
2007-04-30,2,58.10,58.10,58.10,58.10,5000,1,58.1000,0.0094,16467.0,13118.0,5000.0,0.3812,0.033608,0.0000
2007-04-30,2,58.05,58.05,58.05,58.05,2000,1,58.0500,0.0094,16467.0,13118.0,2000.0,0.1525,0.033608,0.0000
2007-04-30,2,58.05,58.05,58.05,58.05,12000,1,58.0500,0.0094,16467.0,13118.0,12000.0,0.9148,0.033608,0.0000
2007-04-30,2,58.05,58.05,58.05,58.05,3500,2,58.0500,0.0094,16467.0,13118.0,1750.0,0.1334,0.033608,0.0000
2007-04-30,2,58.10,58.10,58.10,58.10,1000,1,58.1000,0.0094,16467.0,13118.0,1000.0,0.0762,0.033608,0.0000
2007-04-30,2,58.10,58.10,58.10,58.10,8000,2,58.1000,0.0094,16467.0,13118.0,4000.0,0.3049,0.033608,0.0000
2007-04-30,2,58.10,58.10,58.05,58.10,82000,3,58.0988,0.0094,16467.0,13118.0,27333.0,2.0836,0.033608,4.0973
2007-04-30,2,58.10,58.10,58.10,58.10,5000,4,58.1000,0.0094,16467.0,13118.0,1250.0,0.0953,0.033608,0.0000
2007-04-30,2,58.10,58.10,58.05,58.05,10500,3,58.0833,0.0094,16467.0,13118.0,3500.0,0.2668,0.033608,1.4291
2007-04-30,2,58.05,58.05,58.00,58.00,25500,9,58.0245,0.0094,16467.0,13118.0,2833.0,0.2160,0.033608,0.0862
2007-04-30,2,58.00,58.05,58.00,58.00,21500,4,58.0012,0.0094,16467.0,13118.0,5375.0,0.4097,0.033608,4.1025
2007-04-30,2,58.00,58.00,57.80,57.80,74500,9,57.8916,0.0094,16467.0,13118.0,8278.0,0.6310,0.033608,1.4509
2007-04-30,2,57.80,57.80,57.40,57.40,54500,16,57.6353,0.0094,16467.0,13118.0,3406.0,0.2596,0.016152,6.1266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-07-31,2,88.85,88.85,88.80,88.85,3000,4,88.8417,0.0089,11356.0,6851.0,750.0,0.1095,0.036498,1.8799
2018-07-31,2,88.85,88.90,88.80,88.90,25500,29,88.8569,0.0089,11356.0,6851.0,879.0,0.1283,0.042001,0.7766
2018-07-31,2,88.90,88.90,88.90,88.90,2500,3,88.9000,0.0089,11356.0,6851.0,833.0,0.1216,0.039490,0.0000
2018-07-31,2,88.90,88.90,88.90,88.90,500,1,88.9000,0.0089,11356.0,6851.0,500.0,0.0730,0.023703,0.0000
2018-07-31,2,88.90,88.90,88.85,88.85,5500,7,88.8864,0.0089,11356.0,6851.0,786.0,0.1147,0.036763,1.2826
2018-07-31,2,88.90,88.90,88.90,88.90,2500,3,88.9000,0.0089,11356.0,6851.0,833.0,0.1216,0.038811,0.0000
2018-07-31,2,88.90,88.90,88.90,88.90,1500,3,88.9000,0.0089,11356.0,6851.0,500.0,0.0730,0.023570,0.0000
2018-07-31,2,88.90,88.90,88.85,88.90,4500,7,88.8889,0.0089,11356.0,6851.0,643.0,0.0939,0.030346,1.5639
2018-07-31,2,88.85,89.00,88.85,89.00,171000,40,88.9180,0.0089,11356.0,6851.0,4275.0,0.6240,0.181090,0.7872
2018-07-31,2,89.00,89.00,88.95,89.00,10500,6,88.9619,0.0089,11356.0,6851.0,1750.0,0.2554,0.074924,1.4724
2018-07-31,2,89.00,89.00,88.95,89.00,3500,5,88.9929,0.0089,11356.0,6851.0,700.0,0.1022,0.029897,2.0116
2018-07-31,2,89.00,89.00,89.00,89.00,10000,5,89.0000,0.0089,11356.0,6851.0,2000.0,0.2919,0.080276,0.0000
2018-07-31,2,89.00,89.00,88.95,89.00,2000,4,88.9875,0.0089,11356.0,6851.0,500.0,0.0730,0.020069,1.4048
2018-07-31,2,88.95,89.00,88.95,89.00,139500,65,88.9914,0.0089,11356.0,6851.0,2146.0,0.3132,0.080798,1.8430
2018-07-31,2,89.00,89.20,89.00,89.20,88000,45,89.0889,0.0089,11356.0,6851.0,1956.0,0.2855,0.069817,1.2459
2018-07-31,2,89.20,89.20,89.20,89.20,8500,6,89.2000,0.0089,11356.0,6851.0,1417.0,0.2068,0.050012,0.0000
2018-07-31,2,89.20,89.25,89.20,89.25,9000,10,89.2028,0.0089,11356.0,6851.0,900.0,0.1314,0.031323,2.4884
2018-07-31,2,89.20,89.20,89.15,89.20,30500,19,89.1836,0.0089,11356.0,6851.0,1605.0,0.2343,0.053790,0.9643
2018-07-31,2,89.25,89.25,89.25,89.25,11000,11,89.2500,0.0089,11356.0,6851.0,1000.0,0.1460,0.033161,0.0000
2018-07-31,2,89.25,89.30,89.25,89.30,11000,15,89.2909,0.0089,11356.0,6851.0,733.0,0.1070,0.024388,1.7809
2018-07-31,2,89.30,89.40,89.30,89.40,121000,54,89.3465,0.0089,11356.0,6851.0,2241.0,0.3271,0.070478,0.3917
2018-07-31,2,89.40,89.40,89.35,89.40,23000,26,89.3870,0.0089,11356.0,6851.0,885.0,0.1292,0.027500,1.3426
2018-07-31,2,89.40,89.45,89.40,89.45,102500,45,89.4110,0.0089,11356.0,6851.0,2278.0,0.3325,0.067079,1.5657
2018-07-31,2,89.45,89.45,89.45,89.45,3500,7,89.4500,0.0089,11356.0,6851.0,500.0,0.0730,0.014723,0.0000
2018-07-31,2,89.45,89.50,89.45,89.50,19000,23,89.4724,0.0089,11356.0,6851.0,826.0,0.1206,0.024091,0.2906
2018-07-31,2,89.50,89.50,89.35,89.50,156500,48,89.4534,0.0089,11356.0,6851.0,3260.0,0.4758,0.087999,3.1753
2018-07-31,2,89.50,89.50,89.40,89.40,4500,7,89.4389,0.0089,11356.0,6851.0,643.0,0.0939,0.017290,1.2410
2018-07-31,2,89.45,89.50,89.45,89.50,15500,13,89.4677,0.0089,11356.0,6851.0,1192.0,0.1740,0.031467,0.8159
2018-07-31,2,89.45,89.70,89.45,89.70,161000,100,89.5789,0.0089,11356.0,6851.0,1610.0,0.2350,0.041398,0.4354
2018-07-31,2,89.65,89.65,89.65,89.65,901000,177,89.6500,0.0089,11356.0,6851.0,5090.0,0.7430,0.117740,0.0000

In [179]:
SEHK_2_df[SEHK_2_df['Cost'] != 0].count()

Name                             303970
Open                             303970
High                             303970
Low                              303970
Close                            303970
Volume                           303970
Count                            303970
VWAP                             303970
Volatility                       303970
Daily_Average_Volume             303970
Previous_Daily_Average_Volume    303970
Trading Volume                   303970
Size                             303970
POV                              303970
Cost                             303970
dtype: int64

In [258]:
SEHK_2_data = SEHK_2_df[['Size', 'Volatility', 'POV', 'Cost']]
cp_SEHK_2_data = SEHK_2_data.copy()
SEHK_2_data

              Size  Volatility       POV     Cost
Date_key
2007-04-30  0.0635      0.0094  0.033608  20.4377
2007-04-30  0.0762      0.0094  0.033608   0.0000
2007-04-30  0.1525      0.0094  0.033608   0.0000
2007-04-30  1.9058      0.0094  0.033608   0.0000
2007-04-30  0.1143      0.0094  0.033608   1.4219
2007-04-30  1.1435      0.0094  0.033608   0.0000
2007-04-30  0.1715      0.0094  0.033608   0.0000
2007-04-30  0.1525      0.0094  0.033608   0.0000
2007-04-30  0.1525      0.0094  0.033608   2.8665
2007-04-30  0.1906      0.0094  0.033608   0.0000
2007-04-30  0.4764      0.0094  0.033608   7.5638
2007-04-30  0.5717      0.0094  0.033608   0.0000
2007-04-30  2.7952      0.0094  0.033608   4.8546
2007-04-30  0.1525      0.0094  0.033608   0.0000
2007-04-30  0.4574      0.0094  0.033608   5.2727
2007-04-30  0.0489      0.0094  0.033608   0.0000
2007-04-30  1.5246      0.0094  0.033608   0.0000
2007-04-30  0.3812      0.0094  0.033608   0.0000
2007-04-30  0.1525      0.0094  0.033608   0.0000
2007-04-30  0.9148      0.0094  0.033608   0.0000
2007-04-30  0.1334      0.0094  0.033608   0.0000
2007-04-30  0.0762      0.0094  0.033608   0.0000
2007-04-30  0.3049      0.0094  0.033608   0.0000
2007-04-30  2.0836      0.0094  0.033608   4.0973
2007-04-30  0.0953      0.0094  0.033608   0.0000
2007-04-30  0.2668      0.0094  0.033608   1.4291
2007-04-30  0.2160      0.0094  0.033608   0.0862
2007-04-30  0.4097      0.0094  0.033608   4.1025
2007-04-30  0.6310      0.0094  0.033608   1.4509
2007-04-30  0.2596      0.0094  0.016152   6.1266
...            ...         ...       ...      ...
2018-07-31  0.1095      0.0089  0.036498   1.8799
2018-07-31  0.1283      0.0089  0.042001   0.7766
2018-07-31  0.1216      0.0089  0.039490   0.0000
2018-07-31  0.0730      0.0089  0.023703   0.0000
2018-07-31  0.1147      0.0089  0.036763   1.2826
2018-07-31  0.1216      0.0089  0.038811   0.0000
2018-07-31  0.0730      0.0089  0.023570   0.0000
2018-07-31  0.0939      0.0089  0.030346   1.5639
2018-07-31  0.6240      0.0089  0.181090   0.7872
2018-07-31  0.2554      0.0089  0.074924   1.4724
2018-07-31  0.1022      0.0089  0.029897   2.0116
2018-07-31  0.2919      0.0089  0.080276   0.0000
2018-07-31  0.0730      0.0089  0.020069   1.4048
2018-07-31  0.3132      0.0089  0.080798   1.8430
2018-07-31  0.2855      0.0089  0.069817   1.2459
2018-07-31  0.2068      0.0089  0.050012   0.0000
2018-07-31  0.1314      0.0089  0.031323   2.4884
2018-07-31  0.2343      0.0089  0.053790   0.9643
2018-07-31  0.1460      0.0089  0.033161   0.0000
2018-07-31  0.1070      0.0089  0.024388   1.7809
2018-07-31  0.3271      0.0089  0.070478   0.3917
2018-07-31  0.1292      0.0089  0.027500   1.3426
2018-07-31  0.3325      0.0089  0.067079   1.5657
2018-07-31  0.0730      0.0089  0.014723   0.0000
2018-07-31  0.1206      0.0089  0.024091   0.2906
2018-07-31  0.4758      0.0089  0.087999   3.1753
2018-07-31  0.0939      0.0089  0.017290   1.2410
2018-07-31  0.1740      0.0089  0.031467   0.8159
2018-07-31  0.2350      0.0089  0.041398   0.4354
2018-07-31  0.7430      0.0089  0.117740   0.0000

[654526 rows x 4 columns]

In [239]:
SEHK_2_data['Size'].describe()

count    654526.000000
mean          0.193154
std           0.918671
min           0.000100
25%           0.063800
50%           0.107600
75%           0.207900
max         525.668500
Name: Size, dtype: float64

In [259]:
cp_SEHK_2_data['Size'] = SEHK_2_data['Size'].round(4)
cp_SEHK_2_data['Volatility'] = SEHK_2_data['Volatility'].round(4)
cp_SEHK_2_data['POV'] = SEHK_2_data['POV'].round(4)

In [260]:
# cp_SEHK_2_data['Size'] = pd.cut(SEHK_2_data['Size'], 100, labels=np.arange(0.01, 1.01, 0.01))
# cp_SEHK_2_data['Volatility'] = pd.cut(SEHK_2_data['Volatility'], 100, labels=np.arange(0.01, 1.01, 0.01))
# cp_SEHK_2_data['POV'] = pd.cut(SEHK_2_data['POV'], 100, labels=np.arange(0.001, 1.001, 0.01))

In [261]:
# cp_SEHK_2_data

            Size Volatility    POV     Cost
Date_key
2007-04-30  0.01       0.13  0.031  20.4377
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   1.4219
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   2.8665
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   7.5638
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   4.8546
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   5.2727
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   4.0973
2007-04-30  0.01       0.13  0.031   0.0000
2007-04-30  0.01       0.13  0.031   1.4291
2007-04-30  0.01       0.13  0.031   0.0862
2007-04-30  0.01       0.13  0.031   4.1025
2007-04-30  0.01       0.13  0.031   1.4509
2007-04-30  0.01       0.13  0.011   6.1266
...          ...        ...    ...      ...
2018-07-31  0.01       0.12  0.031   1.8799
2018-07-31  0.01       0.12  0.041   0.7766
2018-07-31  0.01       0.12  0.041   0.0000
2018-07-31  0.01       0.12  0.021   0.0000
2018-07-31  0.01       0.12  0.031   1.2826
2018-07-31  0.01       0.12  0.031   0.0000
2018-07-31  0.01       0.12  0.021   0.0000
2018-07-31  0.01       0.12  0.031   1.5639
2018-07-31  0.01       0.12  0.181   0.7872
2018-07-31  0.01       0.12  0.071   1.4724
2018-07-31  0.01       0.12  0.031   2.0116
2018-07-31  0.01       0.12  0.081   0.0000
2018-07-31  0.01       0.12  0.021   1.4048
2018-07-31  0.01       0.12  0.081   1.8430
2018-07-31  0.01       0.12  0.071   1.2459
2018-07-31  0.01       0.12  0.051   0.0000
2018-07-31  0.01       0.12  0.031   2.4884
2018-07-31  0.01       0.12  0.051   0.9643
2018-07-31  0.01       0.12  0.031   0.0000
2018-07-31  0.01       0.12  0.021   1.7809
2018-07-31  0.01       0.12  0.071   0.3917
2018-07-31  0.01       0.12  0.021   1.3426
2018-07-31  0.01       0.12  0.061   1.5657
2018-07-31  0.01       0.12  0.011   0.0000
2018-07-31  0.01       0.12  0.021   0.2906
2018-07-31  0.01       0.12  0.081   3.1753
2018-07-31  0.01       0.12  0.011   1.2410
2018-07-31  0.01       0.12  0.031   0.8159
2018-07-31  0.01       0.12  0.041   0.4354
2018-07-31  0.01       0.12  0.121   0.0000

[654526 rows x 4 columns]

In [262]:
# test = cp_SEHK_2_data.groupby(['Size', 'Volatility', 'POV']).mean().reset_index().dropna()
# test2 = test[test['Cost'] > 0]
# test2

       Size Volatility    POV       Cost
0      0.01       0.01  0.001   0.406953
1      0.01       0.01  0.011   0.787223
2      0.01       0.01  0.021   1.197706
3      0.01       0.01  0.031   1.246449
4      0.01       0.01  0.041   1.897952
5      0.01       0.01  0.051   1.850171
6      0.01       0.01  0.061   1.785612
7      0.01       0.01  0.071   1.422423
8      0.01       0.01  0.081   1.829410
9      0.01       0.01  0.091   1.532337
10     0.01       0.01  0.101   1.716509
11     0.01       0.01  0.111   1.223260
12     0.01       0.01  0.121   2.463003
13     0.01       0.01  0.131   1.580242
14     0.01       0.01  0.141   1.936905
15     0.01       0.01  0.151   0.962441
16     0.01       0.01  0.161   1.387793
17     0.01       0.01  0.171   2.091686
18     0.01       0.01  0.181   1.383356
19     0.01       0.01  0.191   2.334300
20     0.01       0.01  0.201   1.669940
21     0.01       0.01  0.211   1.939289
22     0.01       0.01  0.221   0.546600
23     0.01       0.01  0.231   3.538200
24     0.01       0.01  0.241   1.920100
25     0.01       0.01  0.251   1.300967
26     0.01       0.01  0.261   1.079367
27     0.01       0.01  0.271   3.766000
28     0.01       0.01  0.281   4.650100
29     0.01       0.01  0.291   1.661250
...     ...        ...    ...        ...
9911   0.01       1.00  0.111   4.122500
9913   0.01       1.00  0.131  25.126300
9914   0.01       1.00  0.141   2.284400
9918   0.01       1.00  0.181   9.786600
10160  0.02       0.02  0.601   0.269200
10171  0.02       0.02  0.711   4.075800
10248  0.02       0.03  0.481   2.634200
10333  0.02       0.04  0.331   0.015300
10337  0.02       0.04  0.371   7.212400
10359  0.02       0.04  0.591   3.449700
10531  0.02       0.06  0.311   1.906000
10544  0.02       0.06  0.441   0.638200
10552  0.02       0.06  0.521   0.818950
10729  0.02       0.08  0.291   3.369200
10737  0.02       0.08  0.371   1.632450
10742  0.02       0.08  0.421   4.842400
10755  0.02       0.08  0.551   0.693100
10845  0.02       0.09  0.451   7.701600
10862  0.02       0.09  0.621   3.727200
10923  0.02       0.10  0.231   1.524650
11135  0.02       0.12  0.351   3.035800
11144  0.02       0.12  0.441   2.882000
11153  0.02       0.12  0.531   0.129700
11154  0.02       0.12  0.541   3.810200
11238  0.02       0.13  0.381   3.845400
11457  0.02       0.15  0.571   3.485200
11636  0.02       0.17  0.361   3.828900
11959  0.02       0.20  0.591   8.982900
30673  0.04       0.07  0.731  70.392900
41068  0.05       0.11  0.681  51.494100

[1752 rows x 4 columns]

In [263]:
# test[test['Cost'] > 0]
test['Size'].describe()

count     2162.00
unique      17.00
top          0.01
freq      1976.00
Name: Size, dtype: float64

In [269]:
SEHK_bin = cp_SEHK_2_data.groupby(['Volatility']).mean()
SEHK_bin.reset_index(inplace=True)
SEHK_bin[['Volatility', 'Cost']].to_csv('SEHK_2_Volatility.csv', index=False)

In [184]:
# test = SEHK_2_data.copy()
# test2 = SEHK_2_data.copy()

In [185]:
SEHK_bin = test.groupby(['Volatility']).mean().reset_index()
SEHK_bin[SEHK_bin['Size'] >= 0]

In [186]:
SEHK_bin.reset_index(inplace=True, drop=True)
SEHK_bin.to_csv('SEHK_2388_MIC.csv', index=False)