In [1]:
# import libraries
import pandas as pd
from datetime import datetime
import numpy as np

In [4]:
# open csv data
csvdf = pd.read_csv('SEHK_2_clean.csv')
csvdf = csvdf[csvdf['Volume'] != 0]
csvdf

,Name,Date,Open,High,Low,Close,Volume,Count,VWAP
0,2,30/4/2007 02:00,59.05,59.05,58.50,58.50,5000,6,58.6550
1,2,30/4/2007 02:01,58.50,58.50,58.50,58.50,1000,1,58.5000
5,2,30/4/2007 02:05,58.35,58.35,58.35,58.35,2000,1,58.3500
8,2,30/4/2007 02:08,58.40,58.40,58.40,58.40,25000,1,58.4000
9,2,30/4/2007 02:09,58.35,58.40,58.35,58.40,3000,2,58.3667
12,2,30/4/2007 02:12,58.40,58.40,58.40,58.40,15000,1,58.4000
15,2,30/4/2007 02:15,58.35,58.35,58.35,58.35,4500,2,58.3500
17,2,30/4/2007 02:17,58.35,58.35,58.35,58.35,2000,1,58.3500
18,2,30/4/2007 02:18,58.30,58.30,58.20,58.20,6000,3,58.2667
19,2,30/4/2007 02:19,58.25,58.25,58.25,58.25,2500,1,58.2500
21,2,30/4/2007 02:21,58.20,58.20,58.10,58.10,25000,4,58.1940
22,2,30/4/2007 02:22,58.10,58.10,58.10,58.10,22500,3,58.1000
23,2,30/4/2007 02:23,58.10,58.15,58.00,58.15,110000,3,58.1032
24,2,30/4/2007 02:24,58.10,58.10,58.10,58.10,2000,1,58.1000
25,2,30/4/2007 02:25,58.10,58.10,58.00,58.00,18000,3,58.0194
26,2,30/4/2007 02:26,58.10,58.10,58.10,58.10,1282,2,58.1000
28,2,30/4/2007 02:28,58.10,58.10,58.10,58.10,20000,1,58.1000
29,2,30/4/2007 02:29,58.10,58.10,58.10,58.10,5000,1,58.1000
30,2,30/4/2007 02:30,58.05,58.05,58.05,58.05,2000,1,58.0500
31,2,30/4/2007 02:31,58.05,58.05,58.05,58.05,12000,1,58.0500
32,2,30/4/2007 02:32,58.05,58.05,58.05,58.05,3500,2,58.0500
33,2,30/4/2007 02:33,58.10,58.10,58.10,58.10,1000,1,58.1000
38,2,30/4/2007 02:38,58.10,58.10,58.10,58.10,8000,2,58.1000
40,2,30/4/2007 02:40,58.10,58.10,58.05,58.10,82000,3,58.0988
41,2,30/4/2007 02:41,58.10,58.10,58.10,58.10,5000,4,58.1000
42,2,30/4/2007 02:42,58.10,58.10,58.05,58.05,10500,3,58.0833
43,2,30/4/2007 02:43,58.05,58.05,58.00,58.00,25500,9,58.0245
44,2,30/4/2007 02:44,58.00,58.05,58.00,58.00,21500,4,58.0012
45,2,30/4/2007 02:45,58.00,58.00,57.80,57.80,74500,9,57.8916
46,2,30/4/2007 02:46,57.80,57.80,57.40,57.40,54500,16,57.6353
...,...,...,...,...,...,...,...,...,...
824195,2,31/7/2018 07:31,88.85,88.85,88.80,88.85,3000,4,88.8417
824196,2,31/7/2018 07:32,88.85,88.90,88.80,88.90,25500,29,88.8569
824197,2,31/7/2018 07:33,88.90,88.90,88.90,88.90,2500,3,88.9000
824198,2,31/7/2018 07:34,88.90,88.90,88.90,88.90,500,1,88.9000
824199,2,31/7/2018 07:35,88.90,88.90,88.85,88.85,5500,7,88.8864
824200,2,31/7/2018 07:36,88.90,88.90,88.90,88.90,2500,3,88.9000
824201,2,31/7/2018 07:37,88.90,88.90,88.90,88.90,1500,3,88.9000
824202,2,31/7/2018 07:38,88.90,88.90,88.85,88.90,4500,7,88.8889
824203,2,31/7/2018 07:39,88.85,89.00,88.85,89.00,171000,40,88.9180
824204,2,31/7/2018 07:40,89.00,89.00,88.95,89.00,10500,6,88.9619
824205,2,31/7/2018 07:41,89.00,89.00,88.95,89.00,3500,5,88.9929
824206,2,31/7/2018 07:42,89.00,89.00,89.00,89.00,10000,5,89.0000
824207,2,31/7/2018 07:43,89.00,89.00,88.95,89.00,2000,4,88.9875
824208,2,31/7/2018 07:44,88.95,89.00,88.95,89.00,139500,65,88.9914
824209,2,31/7/2018 07:45,89.00,89.20,89.00,89.20,88000,45,89.0889
824210,2,31/7/2018 07:46,89.20,89.20,89.20,89.20,8500,6,89.2000
824211,2,31/7/2018 07:47,89.20,89.25,89.20,89.25,9000,10,89.2028
824212,2,31/7/2018 07:48,89.20,89.20,89.15,89.20,30500,19,89.1836
824213,2,31/7/2018 07:49,89.25,89.25,89.25,89.25,11000,11,89.2500
824214,2,31/7/2018 07:50,89.25,89.30,89.25,89.30,11000,15,89.2909
824215,2,31/7/2018 07:51,89.30,89.40,89.30,89.40,121000,54,89.3465
824216,2,31/7/2018 07:52,89.40,89.40,89.35,89.40,23000,26,89.3870
824217,2,31/7/2018 07:53,89.40,89.45,89.40,89.45,102500,45,89.4110
824218,2,31/7/2018 07:54,89.45,89.45,89.45,89.45,3500,7,89.4500
824219,2,31/7/2018 07:55,89.45,89.50,89.45,89.50,19000,23,89.4724
824220,2,31/7/2018 07:56,89.50,89.50,89.35,89.50,156500,48,89.4534
824221,2,31/7/2018 07:57,89.50,89.50,89.40,89.40,4500,7,89.4389
824222,2,31/7/2018 07:58,89.45,89.50,89.45,89.50,15500,13,89.4677
824223,2,31/7/2018 07:59,89.45,89.70,89.45,89.70,161000,100,89.5789
824232,2,31/7/2018 08:08,89.65,89.65,89.65,89.65,901000,177,89.6500

In [5]:
# Set index to Date TimeSeries

csvdf['Date'] = pd.to_datetime(csvdf['Date'], dayfirst=True)
csvdf.set_index('Date', inplace=True)

In [7]:
SEHK_2_df = csvdf[:'2018'].copy()
SEHK_2_df

                     Name   Open   High    Low  Close  Volume  Count     VWAP
Date
2007-04-30 02:00:00     2  59.05  59.05  58.50  58.50    5000      6  58.6550
2007-04-30 02:01:00     2  58.50  58.50  58.50  58.50    1000      1  58.5000
2007-04-30 02:05:00     2  58.35  58.35  58.35  58.35    2000      1  58.3500
2007-04-30 02:08:00     2  58.40  58.40  58.40  58.40   25000      1  58.4000
2007-04-30 02:09:00     2  58.35  58.40  58.35  58.40    3000      2  58.3667
2007-04-30 02:12:00     2  58.40  58.40  58.40  58.40   15000      1  58.4000
2007-04-30 02:15:00     2  58.35  58.35  58.35  58.35    4500      2  58.3500
2007-04-30 02:17:00     2  58.35  58.35  58.35  58.35    2000      1  58.3500
2007-04-30 02:18:00     2  58.30  58.30  58.20  58.20    6000      3  58.2667
2007-04-30 02:19:00     2  58.25  58.25  58.25  58.25    2500      1  58.2500
2007-04-30 02:21:00     2  58.20  58.20  58.10  58.10   25000      4  58.1940
2007-04-30 02:22:00     2  58.10  58.10  58.10  58.10   22500      3  58.1000
2007-04-30 02:23:00     2  58.10  58.15  58.00  58.15  110000      3  58.1032
2007-04-30 02:24:00     2  58.10  58.10  58.10  58.10    2000      1  58.1000
2007-04-30 02:25:00     2  58.10  58.10  58.00  58.00   18000      3  58.0194
2007-04-30 02:26:00     2  58.10  58.10  58.10  58.10    1282      2  58.1000
2007-04-30 02:28:00     2  58.10  58.10  58.10  58.10   20000      1  58.1000
2007-04-30 02:29:00     2  58.10  58.10  58.10  58.10    5000      1  58.1000
2007-04-30 02:30:00     2  58.05  58.05  58.05  58.05    2000      1  58.0500
2007-04-30 02:31:00     2  58.05  58.05  58.05  58.05   12000      1  58.0500
2007-04-30 02:32:00     2  58.05  58.05  58.05  58.05    3500      2  58.0500
2007-04-30 02:33:00     2  58.10  58.10  58.10  58.10    1000      1  58.1000
2007-04-30 02:38:00     2  58.10  58.10  58.10  58.10    8000      2  58.1000
2007-04-30 02:40:00     2  58.10  58.10  58.05  58.10   82000      3  58.0988
2007-04-30 02:41:00     2  58.10  58.10  58.10  58.10    5000      4  58.1000
2007-04-30 02:42:00     2  58.10  58.10  58.05  58.05   10500      3  58.0833
2007-04-30 02:43:00     2  58.05  58.05  58.00  58.00   25500      9  58.0245
2007-04-30 02:44:00     2  58.00  58.05  58.00  58.00   21500      4  58.0012
2007-04-30 02:45:00     2  58.00  58.00  57.80  57.80   74500      9  57.8916
2007-04-30 02:46:00     2  57.80  57.80  57.40  57.40   54500     16  57.6353
...                   ...    ...    ...    ...    ...     ...    ...      ...
2018-07-31 07:31:00     2  88.85  88.85  88.80  88.85    3000      4  88.8417
2018-07-31 07:32:00     2  88.85  88.90  88.80  88.90   25500     29  88.8569
2018-07-31 07:33:00     2  88.90  88.90  88.90  88.90    2500      3  88.9000
2018-07-31 07:34:00     2  88.90  88.90  88.90  88.90     500      1  88.9000
2018-07-31 07:35:00     2  88.90  88.90  88.85  88.85    5500      7  88.8864
2018-07-31 07:36:00     2  88.90  88.90  88.90  88.90    2500      3  88.9000
2018-07-31 07:37:00     2  88.90  88.90  88.90  88.90    1500      3  88.9000
2018-07-31 07:38:00     2  88.90  88.90  88.85  88.90    4500      7  88.8889
2018-07-31 07:39:00     2  88.85  89.00  88.85  89.00  171000     40  88.9180
2018-07-31 07:40:00     2  89.00  89.00  88.95  89.00   10500      6  88.9619
2018-07-31 07:41:00     2  89.00  89.00  88.95  89.00    3500      5  88.9929
2018-07-31 07:42:00     2  89.00  89.00  89.00  89.00   10000      5  89.0000
2018-07-31 07:43:00     2  89.00  89.00  88.95  89.00    2000      4  88.9875
2018-07-31 07:44:00     2  88.95  89.00  88.95  89.00  139500     65  88.9914
2018-07-31 07:45:00     2  89.00  89.20  89.00  89.20   88000     45  89.0889
2018-07-31 07:46:00     2  89.20  89.20  89.20  89.20    8500      6  89.2000
2018-07-31 07:47:00     2  89.20  89.25  89.20  89.25    9000     10  89.2028
2018-07-31 07:48:00     2  89.20  89.20  89.15  89.20   30500     19  89.1836
2018-07-31 07:49:00     2  89.25  89.25  89.25  89.25   11000     11  89.2500
2018-07-31 07:50:00     2  89.25  89.30  89.25  89.30   11000     15  89.2909
2018-07-31 07:51:00     2  89.30  89.40  89.30  89.40  121000     54  89.3465
2018-07-31 07:52:00     2  89.40  89.40  89.35  89.40   23000     26  89.3870
2018-07-31 07:53:00     2  89.40  89.45  89.40  89.45  102500     45  89.4110
2018-07-31 07:54:00     2  89.45  89.45  89.45  89.45    3500      7  89.4500
2018-07-31 07:55:00     2  89.45  89.50  89.45  89.50   19000     23  89.4724
2018-07-31 07:56:00     2  89.50  89.50  89.35  89.50  156500     48  89.4534
2018-07-31 07:57:00     2  89.50  89.50  89.40  89.40    4500      7  89.4389
2018-07-31 07:58:00     2  89.45  89.50  89.45  89.50   15500     13  89.4677
2018-07-31 07:59:00     2  89.45  89.70  89.45  89.70  161000    100  89.5789
2018-07-31 08:08:00     2  89.65  89.65  89.65  89.65  901000    177  89.6500

[654526 rows x 8 columns]

In [8]:
day_SEHK_2_df = SEHK_2_df.resample('B').last()
day_SEHK_2_df

            Name   Open   High    Low  Close     Volume  Count     VWAP
Date
2007-04-30   2.0  57.50  57.50  57.30  57.35    79000.0   34.0  57.4120
2007-05-01   NaN    NaN    NaN    NaN    NaN        NaN    NaN      NaN
2007-05-02   2.0  58.75  58.75  58.45  58.55   113500.0   28.0  58.6308
2007-05-03   2.0  59.05  59.05  59.05  59.05     3500.0    3.0  59.0500
2007-05-04   2.0  58.70  58.70  58.45  58.45    50500.0   18.0  58.5668
2007-05-07   2.0  58.10  58.10  58.05  58.10   125500.0   17.0  58.0580
2007-05-08   2.0  57.20  57.30  57.10  57.30   183000.0   29.0  57.2123
2007-05-09   2.0  57.75  58.00  57.75  58.00    49500.0   17.0  57.9288
2007-05-10   2.0  57.25  57.45  57.25  57.45    76500.0   15.0  57.3915
2007-05-11   2.0  57.05  57.10  57.05  57.10    93000.0    9.0  57.0847
2007-05-14   2.0  56.80  56.85  56.80  56.85    71000.0   19.0  56.8218
2007-05-15   2.0  57.15  57.20  56.90  57.20    37000.0   24.0  57.1480
2007-05-16   2.0  57.00  57.15  56.90  56.90    25500.0   10.0  57.0039
2007-05-17   2.0  56.85  57.10  56.85  57.10   146500.0   14.0  56.9657
2007-05-18   2.0  56.70  56.80  56.70  56.80     6500.0    4.0  56.7615
2007-05-21   2.0  56.50  56.50  56.40  56.40   147000.0   15.0  56.4182
2007-05-22   2.0  55.45  55.50  55.40  55.45    73500.0   21.0  55.4381
2007-05-23   2.0  55.05  55.10  55.00  55.05   206500.0   22.0  55.0150
2007-05-24   NaN    NaN    NaN    NaN    NaN        NaN    NaN      NaN
2007-05-25   2.0  54.60  54.60  54.50  54.55    57500.0   14.0  54.5491
2007-05-28   2.0  54.75  54.75  54.70  54.70    65000.0   13.0  54.7069
2007-05-29   2.0  54.65  54.65  54.60  54.65   161500.0   13.0  54.6053
2007-05-30   2.0  54.90  54.90  54.75  54.80   181000.0   35.0  54.7775
2007-05-31   2.0  55.10  55.15  55.00  55.05  3734500.0   75.0  55.0278
2007-06-01   2.0  55.45  55.45  55.05  55.05   142500.0   23.0  55.3068
2007-06-04   2.0  54.80  54.85  54.75  54.75   165500.0   15.0  54.7937
2007-06-05   2.0  54.45  54.45  54.25  54.40   246500.0   29.0  54.3165
2007-06-06   2.0  54.80  54.85  54.45  54.45    37500.0   12.0  54.7420
2007-06-07   2.0  54.70  54.70  54.30  54.30    82000.0   14.0  54.5488
2007-06-08   2.0  53.75  53.75  53.70  53.75   137000.0   16.0  53.7235
...          ...    ...    ...    ...    ...        ...    ...      ...
2018-06-20   2.0  80.70  80.75  80.70  80.75     9000.0   13.0  80.7194
2018-06-21   2.0  80.15  80.25  80.05  80.25     5000.0    7.0  80.1800
2018-06-22   2.0  80.40  80.40  80.25  80.25     4000.0    8.0  80.3625
2018-06-25   2.0  80.25  80.50  80.20  80.25    28000.0   31.0  80.2768
2018-06-26   2.0  82.75  82.75  82.65  82.75    35000.0   48.0  82.7071
2018-06-27   2.0  83.40  83.45  83.40  83.40    68000.0   64.0  83.4147
2018-06-28   2.0  84.25  84.40  84.20  84.40    20500.0   30.0  84.3439
2018-06-29   2.0  84.50  84.50  84.50  84.50   735000.0  169.0  84.5000
2018-07-02   NaN    NaN    NaN    NaN    NaN        NaN    NaN      NaN
2018-07-03   2.0  84.45  84.50  84.40  84.40    24000.0   31.0  84.4458
2018-07-04   2.0  87.30  87.35  87.30  87.35    16000.0   21.0  87.3203
2018-07-05   2.0  87.80  87.85  87.70  87.85    20500.0   25.0  87.7902
2018-07-06   2.0  88.00  88.00  87.95  88.00    13500.0   19.0  87.9852
2018-07-09   2.0  88.00  88.00  87.95  87.95    21000.0   25.0  87.9798
2018-07-10   2.0  87.55  87.55  87.45  87.45    12500.0   20.0  87.5080
2018-07-11   2.0  86.75  86.75  86.60  86.75     5500.0    9.0  86.7136
2018-07-12   2.0  87.20  87.20  87.10  87.20     9500.0   13.0  87.1842
2018-07-13   2.0  87.40  87.45  87.30  87.35    24500.0   18.0  87.3582
2018-07-16   2.0  88.40  88.40  88.35  88.40    36000.0   31.0  88.3986
2018-07-17   2.0  87.90  87.90  87.90  87.90     1500.0    2.0  87.9000
2018-07-18   2.0  88.25  88.40  88.25  88.30    38500.0   45.0  88.3247
2018-07-19   2.0  88.50  88.55  88.45  88.45    12500.0   16.0  88.4760
2018-07-20   2.0  89.35  89.35  89.20  89.30    32000.0   30.0  89.2750
2018-07-23   2.0  89.30  89.30  89.25  89.30    18000.0   29.0  89.2764
2018-07-24   2.0  88.80  89.15  88.80  88.90    20500.0   33.0  88.8854
2018-07-25   2.0  88.40  88.45  88.40  88.45    11000.0   13.0  88.4318
2018-07-26   2.0  88.50  88.50  88.45  88.45    21000.0   28.0  88.4964
2018-07-27   2.0  88.00  88.00  87.90  87.95    13000.0   18.0  87.9385
2018-07-30   2.0  88.70  88.75  88.65  88.65    25000.0   21.0  88.6880
2018-07-31   2.0  89.65  89.65  89.65  89.65   901000.0  177.0  89.6500

[2937 rows x 8 columns]

In [9]:
day_SEHK_2_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2937 entries, 2007-04-30 to 2018-07-31
Freq: B
Data columns (total 8 columns):
Name      2772 non-null float64
Open      2772 non-null float64
High      2772 non-null float64
Low       2772 non-null float64
Close     2772 non-null float64
Volume    2772 non-null float64
Count     2772 non-null float64
VWAP      2772 non-null float64
dtypes: float64(8)
memory usage: 206.5 KB

In [10]:
day_SEHK_2_df.dropna(inplace=True)

In [11]:
day_SEHK_2_df

            Name   Open   High    Low  Close     Volume  Count     VWAP
Date
2007-04-30   2.0  57.50  57.50  57.30  57.35    79000.0   34.0  57.4120
2007-05-02   2.0  58.75  58.75  58.45  58.55   113500.0   28.0  58.6308
2007-05-03   2.0  59.05  59.05  59.05  59.05     3500.0    3.0  59.0500
2007-05-04   2.0  58.70  58.70  58.45  58.45    50500.0   18.0  58.5668
2007-05-07   2.0  58.10  58.10  58.05  58.10   125500.0   17.0  58.0580
2007-05-08   2.0  57.20  57.30  57.10  57.30   183000.0   29.0  57.2123
2007-05-09   2.0  57.75  58.00  57.75  58.00    49500.0   17.0  57.9288
2007-05-10   2.0  57.25  57.45  57.25  57.45    76500.0   15.0  57.3915
2007-05-11   2.0  57.05  57.10  57.05  57.10    93000.0    9.0  57.0847
2007-05-14   2.0  56.80  56.85  56.80  56.85    71000.0   19.0  56.8218
2007-05-15   2.0  57.15  57.20  56.90  57.20    37000.0   24.0  57.1480
2007-05-16   2.0  57.00  57.15  56.90  56.90    25500.0   10.0  57.0039
2007-05-17   2.0  56.85  57.10  56.85  57.10   146500.0   14.0  56.9657
2007-05-18   2.0  56.70  56.80  56.70  56.80     6500.0    4.0  56.7615
2007-05-21   2.0  56.50  56.50  56.40  56.40   147000.0   15.0  56.4182
2007-05-22   2.0  55.45  55.50  55.40  55.45    73500.0   21.0  55.4381
2007-05-23   2.0  55.05  55.10  55.00  55.05   206500.0   22.0  55.0150
2007-05-25   2.0  54.60  54.60  54.50  54.55    57500.0   14.0  54.5491
2007-05-28   2.0  54.75  54.75  54.70  54.70    65000.0   13.0  54.7069
2007-05-29   2.0  54.65  54.65  54.60  54.65   161500.0   13.0  54.6053
2007-05-30   2.0  54.90  54.90  54.75  54.80   181000.0   35.0  54.7775
2007-05-31   2.0  55.10  55.15  55.00  55.05  3734500.0   75.0  55.0278
2007-06-01   2.0  55.45  55.45  55.05  55.05   142500.0   23.0  55.3068
2007-06-04   2.0  54.80  54.85  54.75  54.75   165500.0   15.0  54.7937
2007-06-05   2.0  54.45  54.45  54.25  54.40   246500.0   29.0  54.3165
2007-06-06   2.0  54.80  54.85  54.45  54.45    37500.0   12.0  54.7420
2007-06-07   2.0  54.70  54.70  54.30  54.30    82000.0   14.0  54.5488
2007-06-08   2.0  53.75  53.75  53.70  53.75   137000.0   16.0  53.7235
2007-06-11   2.0  54.00  54.25  53.85  54.00   149500.0   18.0  54.1189
2007-06-12   2.0  53.50  53.60  53.30  53.55    79500.0   15.0  53.4821
...          ...    ...    ...    ...    ...        ...    ...      ...
2018-06-19   2.0  80.15  80.20  80.10  80.10    26000.0   30.0  80.1702
2018-06-20   2.0  80.70  80.75  80.70  80.75     9000.0   13.0  80.7194
2018-06-21   2.0  80.15  80.25  80.05  80.25     5000.0    7.0  80.1800
2018-06-22   2.0  80.40  80.40  80.25  80.25     4000.0    8.0  80.3625
2018-06-25   2.0  80.25  80.50  80.20  80.25    28000.0   31.0  80.2768
2018-06-26   2.0  82.75  82.75  82.65  82.75    35000.0   48.0  82.7071
2018-06-27   2.0  83.40  83.45  83.40  83.40    68000.0   64.0  83.4147
2018-06-28   2.0  84.25  84.40  84.20  84.40    20500.0   30.0  84.3439
2018-06-29   2.0  84.50  84.50  84.50  84.50   735000.0  169.0  84.5000
2018-07-03   2.0  84.45  84.50  84.40  84.40    24000.0   31.0  84.4458
2018-07-04   2.0  87.30  87.35  87.30  87.35    16000.0   21.0  87.3203
2018-07-05   2.0  87.80  87.85  87.70  87.85    20500.0   25.0  87.7902
2018-07-06   2.0  88.00  88.00  87.95  88.00    13500.0   19.0  87.9852
2018-07-09   2.0  88.00  88.00  87.95  87.95    21000.0   25.0  87.9798
2018-07-10   2.0  87.55  87.55  87.45  87.45    12500.0   20.0  87.5080
2018-07-11   2.0  86.75  86.75  86.60  86.75     5500.0    9.0  86.7136
2018-07-12   2.0  87.20  87.20  87.10  87.20     9500.0   13.0  87.1842
2018-07-13   2.0  87.40  87.45  87.30  87.35    24500.0   18.0  87.3582
2018-07-16   2.0  88.40  88.40  88.35  88.40    36000.0   31.0  88.3986
2018-07-17   2.0  87.90  87.90  87.90  87.90     1500.0    2.0  87.9000
2018-07-18   2.0  88.25  88.40  88.25  88.30    38500.0   45.0  88.3247
2018-07-19   2.0  88.50  88.55  88.45  88.45    12500.0   16.0  88.4760
2018-07-20   2.0  89.35  89.35  89.20  89.30    32000.0   30.0  89.2750
2018-07-23   2.0  89.30  89.30  89.25  89.30    18000.0   29.0  89.2764
2018-07-24   2.0  88.80  89.15  88.80  88.90    20500.0   33.0  88.8854
2018-07-25   2.0  88.40  88.45  88.40  88.45    11000.0   13.0  88.4318
2018-07-26   2.0  88.50  88.50  88.45  88.45    21000.0   28.0  88.4964
2018-07-27   2.0  88.00  88.00  87.90  87.95    13000.0   18.0  87.9385
2018-07-30   2.0  88.70  88.75  88.65  88.65    25000.0   21.0  88.6880
2018-07-31   2.0  89.65  89.65  89.65  89.65   901000.0  177.0  89.6500

[2772 rows x 8 columns]

In [12]:
# Compute daily return
day_SEHK_2_df['Return'] = day_SEHK_2_df['Close'][1:].values / day_SEHK_2_df['Close'][:-1] - 1

In [13]:
# Fill missing daily return value with previous return
day_SEHK_2_df.fillna(day_SEHK_2_df['Return'].mean(), inplace=True)

In [14]:
day_SEHK_2_df

,Name,Open,High,Low,Close,Volume,Count,VWAP,Return
Date,,,,,,,,,
2007-04-30,2.0,57.50,57.50,57.30,57.35,79000.0,34.0,57.4120,0.020924
2007-05-02,2.0,58.75,58.75,58.45,58.55,113500.0,28.0,58.6308,0.008540
2007-05-03,2.0,59.05,59.05,59.05,59.05,3500.0,3.0,59.0500,-0.010161
2007-05-04,2.0,58.70,58.70,58.45,58.45,50500.0,18.0,58.5668,-0.005988
2007-05-07,2.0,58.10,58.10,58.05,58.10,125500.0,17.0,58.0580,-0.013769
2007-05-08,2.0,57.20,57.30,57.10,57.30,183000.0,29.0,57.2123,0.012216
2007-05-09,2.0,57.75,58.00,57.75,58.00,49500.0,17.0,57.9288,-0.009483
2007-05-10,2.0,57.25,57.45,57.25,57.45,76500.0,15.0,57.3915,-0.006092
2007-05-11,2.0,57.05,57.10,57.05,57.10,93000.0,9.0,57.0847,-0.004378
2007-05-14,2.0,56.80,56.85,56.80,56.85,71000.0,19.0,56.8218,0.006157
2007-05-15,2.0,57.15,57.20,56.90,57.20,37000.0,24.0,57.1480,-0.005245
2007-05-16,2.0,57.00,57.15,56.90,56.90,25500.0,10.0,57.0039,0.003515
2007-05-17,2.0,56.85,57.10,56.85,57.10,146500.0,14.0,56.9657,-0.005254
2007-05-18,2.0,56.70,56.80,56.70,56.80,6500.0,4.0,56.7615,-0.007042
2007-05-21,2.0,56.50,56.50,56.40,56.40,147000.0,15.0,56.4182,-0.016844
2007-05-22,2.0,55.45,55.50,55.40,55.45,73500.0,21.0,55.4381,-0.007214
2007-05-23,2.0,55.05,55.10,55.00,55.05,206500.0,22.0,55.0150,-0.009083
2007-05-25,2.0,54.60,54.60,54.50,54.55,57500.0,14.0,54.5491,0.002750
2007-05-28,2.0,54.75,54.75,54.70,54.70,65000.0,13.0,54.7069,-0.000914
2007-05-29,2.0,54.65,54.65,54.60,54.65,161500.0,13.0,54.6053,0.002745
2007-05-30,2.0,54.90,54.90,54.75,54.80,181000.0,35.0,54.7775,0.004562
2007-05-31,2.0,55.10,55.15,55.00,55.05,3734500.0,75.0,55.0278,0.000000
2007-06-01,2.0,55.45,55.45,55.05,55.05,142500.0,23.0,55.3068,-0.005450
2007-06-04,2.0,54.80,54.85,54.75,54.75,165500.0,15.0,54.7937,-0.006393
2007-06-05,2.0,54.45,54.45,54.25,54.40,246500.0,29.0,54.3165,0.000919
2007-06-06,2.0,54.80,54.85,54.45,54.45,37500.0,12.0,54.7420,-0.002755
2007-06-07,2.0,54.70,54.70,54.30,54.30,82000.0,14.0,54.5488,-0.010129
2007-06-08,2.0,53.75,53.75,53.70,53.75,137000.0,16.0,53.7235,0.004651
2007-06-11,2.0,54.00,54.25,53.85,54.00,149500.0,18.0,54.1189,-0.008333
2007-06-12,2.0,53.50,53.60,53.30,53.55,79500.0,15.0,53.4821,-0.000934
...,...,...,...,...,...,...,...,...,...
2018-06-19,2.0,80.15,80.20,80.10,80.10,26000.0,30.0,80.1702,0.008115
2018-06-20,2.0,80.70,80.75,80.70,80.75,9000.0,13.0,80.7194,-0.006192
2018-06-21,2.0,80.15,80.25,80.05,80.25,5000.0,7.0,80.1800,0.000000
2018-06-22,2.0,80.40,80.40,80.25,80.25,4000.0,8.0,80.3625,0.000000
2018-06-25,2.0,80.25,80.50,80.20,80.25,28000.0,31.0,80.2768,0.031153
2018-06-26,2.0,82.75,82.75,82.65,82.75,35000.0,48.0,82.7071,0.007855
2018-06-27,2.0,83.40,83.45,83.40,83.40,68000.0,64.0,83.4147,0.011990
2018-06-28,2.0,84.25,84.40,84.20,84.40,20500.0,30.0,84.3439,0.001185
2018-06-29,2.0,84.50,84.50,84.50,84.50,735000.0,169.0,84.5000,-0.001183
2018-07-03,2.0,84.45,84.50,84.40,84.40,24000.0,31.0,84.4458,0.034953
2018-07-04,2.0,87.30,87.35,87.30,87.35,16000.0,21.0,87.3203,0.005724
2018-07-05,2.0,87.80,87.85,87.70,87.85,20500.0,25.0,87.7902,0.001707
2018-07-06,2.0,88.00,88.00,87.95,88.00,13500.0,19.0,87.9852,-0.000568
2018-07-09,2.0,88.00,88.00,87.95,87.95,21000.0,25.0,87.9798,-0.005685
2018-07-10,2.0,87.55,87.55,87.45,87.45,12500.0,20.0,87.5080,-0.008005
2018-07-11,2.0,86.75,86.75,86.60,86.75,5500.0,9.0,86.7136,0.005187
2018-07-12,2.0,87.20,87.20,87.10,87.20,9500.0,13.0,87.1842,0.001720
2018-07-13,2.0,87.40,87.45,87.30,87.35,24500.0,18.0,87.3582,0.012021
2018-07-16,2.0,88.40,88.40,88.35,88.40,36000.0,31.0,88.3986,-0.005656
2018-07-17,2.0,87.90,87.90,87.90,87.90,1500.0,2.0,87.9000,0.004551
2018-07-18,2.0,88.25,88.40,88.25,88.30,38500.0,45.0,88.3247,0.001699
2018-07-19,2.0,88.50,88.55,88.45,88.45,12500.0,16.0,88.4760,0.009610
2018-07-20,2.0,89.35,89.35,89.20,89.30,32000.0,30.0,89.2750,0.000000
2018-07-23,2.0,89.30,89.30,89.25,89.30,18000.0,29.0,89.2764,-0.004479
2018-07-24,2.0,88.80,89.15,88.80,88.90,20500.0,33.0,88.8854,-0.005062
2018-07-25,2.0,88.40,88.45,88.40,88.45,11000.0,13.0,88.4318,0.000000
2018-07-26,2.0,88.50,88.50,88.45,88.45,21000.0,28.0,88.4964,-0.005653
2018-07-27,2.0,88.00,88.00,87.90,87.95,13000.0,18.0,87.9385,0.007959
2018-07-30,2.0,88.70,88.75,88.65,88.65,25000.0,21.0,88.6880,0.011280
2018-07-31,2.0,89.65,89.65,89.65,89.65,901000.0,177.0,89.6500,0.000222

In [15]:
# Compute 25-day volatility

day_SEHK_2_df['Volatility'] = day_SEHK_2_df['Return'].rolling(25).std()
day_SEHK_2_df.fillna(day_SEHK_2_df['Volatility'].mean(), inplace=True)

In [16]:
day_SEHK_2_df

,Name,Open,High,Low,Close,Volume,Count,VWAP,Return,Volatility
Date,,,,,,,,,,
2007-04-30,2.0,57.50,57.50,57.30,57.35,79000.0,34.0,57.4120,0.020924,0.009436
2007-05-02,2.0,58.75,58.75,58.45,58.55,113500.0,28.0,58.6308,0.008540,0.009436
2007-05-03,2.0,59.05,59.05,59.05,59.05,3500.0,3.0,59.0500,-0.010161,0.009436
2007-05-04,2.0,58.70,58.70,58.45,58.45,50500.0,18.0,58.5668,-0.005988,0.009436
2007-05-07,2.0,58.10,58.10,58.05,58.10,125500.0,17.0,58.0580,-0.013769,0.009436
2007-05-08,2.0,57.20,57.30,57.10,57.30,183000.0,29.0,57.2123,0.012216,0.009436
2007-05-09,2.0,57.75,58.00,57.75,58.00,49500.0,17.0,57.9288,-0.009483,0.009436
2007-05-10,2.0,57.25,57.45,57.25,57.45,76500.0,15.0,57.3915,-0.006092,0.009436
2007-05-11,2.0,57.05,57.10,57.05,57.10,93000.0,9.0,57.0847,-0.004378,0.009436
2007-05-14,2.0,56.80,56.85,56.80,56.85,71000.0,19.0,56.8218,0.006157,0.009436
2007-05-15,2.0,57.15,57.20,56.90,57.20,37000.0,24.0,57.1480,-0.005245,0.009436
2007-05-16,2.0,57.00,57.15,56.90,56.90,25500.0,10.0,57.0039,0.003515,0.009436
2007-05-17,2.0,56.85,57.10,56.85,57.10,146500.0,14.0,56.9657,-0.005254,0.009436
2007-05-18,2.0,56.70,56.80,56.70,56.80,6500.0,4.0,56.7615,-0.007042,0.009436
2007-05-21,2.0,56.50,56.50,56.40,56.40,147000.0,15.0,56.4182,-0.016844,0.009436
2007-05-22,2.0,55.45,55.50,55.40,55.45,73500.0,21.0,55.4381,-0.007214,0.009436
2007-05-23,2.0,55.05,55.10,55.00,55.05,206500.0,22.0,55.0150,-0.009083,0.009436
2007-05-25,2.0,54.60,54.60,54.50,54.55,57500.0,14.0,54.5491,0.002750,0.009436
2007-05-28,2.0,54.75,54.75,54.70,54.70,65000.0,13.0,54.7069,-0.000914,0.009436
2007-05-29,2.0,54.65,54.65,54.60,54.65,161500.0,13.0,54.6053,0.002745,0.009436
2007-05-30,2.0,54.90,54.90,54.75,54.80,181000.0,35.0,54.7775,0.004562,0.009436
2007-05-31,2.0,55.10,55.15,55.00,55.05,3734500.0,75.0,55.0278,0.000000,0.009436
2007-06-01,2.0,55.45,55.45,55.05,55.05,142500.0,23.0,55.3068,-0.005450,0.009436
2007-06-04,2.0,54.80,54.85,54.75,54.75,165500.0,15.0,54.7937,-0.006393,0.009436
2007-06-05,2.0,54.45,54.45,54.25,54.40,246500.0,29.0,54.3165,0.000919,0.008447
2007-06-06,2.0,54.80,54.85,54.45,54.45,37500.0,12.0,54.7420,-0.002755,0.006961
2007-06-07,2.0,54.70,54.70,54.30,54.30,82000.0,14.0,54.5488,-0.010129,0.006669
2007-06-08,2.0,53.75,53.75,53.70,53.75,137000.0,16.0,53.7235,0.004651,0.006731
2007-06-11,2.0,54.00,54.25,53.85,54.00,149500.0,18.0,54.1189,-0.008333,0.006789
2007-06-12,2.0,53.50,53.60,53.30,53.55,79500.0,15.0,53.4821,-0.000934,0.006435
...,...,...,...,...,...,...,...,...,...,...
2018-06-19,2.0,80.15,80.20,80.10,80.10,26000.0,30.0,80.1702,0.008115,0.009413
2018-06-20,2.0,80.70,80.75,80.70,80.75,9000.0,13.0,80.7194,-0.006192,0.008983
2018-06-21,2.0,80.15,80.25,80.05,80.25,5000.0,7.0,80.1800,0.000000,0.008782
2018-06-22,2.0,80.40,80.40,80.25,80.25,4000.0,8.0,80.3625,0.000000,0.008770
2018-06-25,2.0,80.25,80.50,80.20,80.25,28000.0,31.0,80.2768,0.031153,0.010753
2018-06-26,2.0,82.75,82.75,82.65,82.75,35000.0,48.0,82.7071,0.007855,0.009861
2018-06-27,2.0,83.40,83.45,83.40,83.40,68000.0,64.0,83.4147,0.011990,0.009796
2018-06-28,2.0,84.25,84.40,84.20,84.40,20500.0,30.0,84.3439,0.001185,0.009530
2018-06-29,2.0,84.50,84.50,84.50,84.50,735000.0,169.0,84.5000,-0.001183,0.009491
2018-07-03,2.0,84.45,84.50,84.40,84.40,24000.0,31.0,84.4458,0.034953,0.011534
2018-07-04,2.0,87.30,87.35,87.30,87.35,16000.0,21.0,87.3203,0.005724,0.011349
2018-07-05,2.0,87.80,87.85,87.70,87.85,20500.0,25.0,87.7902,0.001707,0.011320
2018-07-06,2.0,88.00,88.00,87.95,88.00,13500.0,19.0,87.9852,-0.000568,0.011281
2018-07-09,2.0,88.00,88.00,87.95,87.95,21000.0,25.0,87.9798,-0.005685,0.011065
2018-07-10,2.0,87.55,87.55,87.45,87.45,12500.0,20.0,87.5080,-0.008005,0.011218
2018-07-11,2.0,86.75,86.75,86.60,86.75,5500.0,9.0,86.7136,0.005187,0.011223
2018-07-12,2.0,87.20,87.20,87.10,87.20,9500.0,13.0,87.1842,0.001720,0.011179
2018-07-13,2.0,87.40,87.45,87.30,87.35,24500.0,18.0,87.3582,0.012021,0.011172
2018-07-16,2.0,88.40,88.40,88.35,88.40,36000.0,31.0,88.3986,-0.005656,0.010857
2018-07-17,2.0,87.90,87.90,87.90,87.90,1500.0,2.0,87.9000,0.004551,0.010827
2018-07-18,2.0,88.25,88.40,88.25,88.30,38500.0,45.0,88.3247,0.001699,0.010824
2018-07-19,2.0,88.50,88.55,88.45,88.45,12500.0,16.0,88.4760,0.009610,0.010802
2018-07-20,2.0,89.35,89.35,89.20,89.30,32000.0,30.0,89.2750,0.000000,0.010684
2018-07-23,2.0,89.30,89.30,89.25,89.30,18000.0,29.0,89.2764,-0.004479,0.010768
2018-07-24,2.0,88.80,89.15,88.80,88.90,20500.0,33.0,88.8854,-0.005062,0.010408
2018-07-25,2.0,88.40,88.45,88.40,88.45,11000.0,13.0,88.4318,0.000000,0.010402
2018-07-26,2.0,88.50,88.50,88.45,88.45,21000.0,28.0,88.4964,-0.005653,0.010381
2018-07-27,2.0,88.00,88.00,87.90,87.95,13000.0,18.0,87.9385,0.007959,0.010384
2018-07-30,2.0,88.70,88.75,88.65,88.65,25000.0,21.0,88.6880,0.011280,0.010446
2018-07-31,2.0,89.65,89.65,89.65,89.65,901000.0,177.0,89.6500,0.000222,0.008870

In [17]:
day_SEHK_2_df['Date_key'] = day_SEHK_2_df.index.date
SEHK_2_df['Date_key'] = SEHK_2_df.index.date

In [17]:
SEHK_2_df['Volatility'] = day_SEHK_2_df['Volatility']
SEHK_2_df.fillna(SEHK_2_df['Volatility'].mean(), inplace=True)

In [18]:
day_SEHK_2_df.set_index('Date_key', inplace=True)
day_SEHK_2_df

,Name,Open,High,Low,Close,Volume,Count,VWAP,Return,Volatility
Date_key,,,,,,,,,,
2007-04-30,2.0,57.50,57.50,57.30,57.35,79000.0,34.0,57.4120,0.020924,0.009436
2007-05-02,2.0,58.75,58.75,58.45,58.55,113500.0,28.0,58.6308,0.008540,0.009436
2007-05-03,2.0,59.05,59.05,59.05,59.05,3500.0,3.0,59.0500,-0.010161,0.009436
2007-05-04,2.0,58.70,58.70,58.45,58.45,50500.0,18.0,58.5668,-0.005988,0.009436
2007-05-07,2.0,58.10,58.10,58.05,58.10,125500.0,17.0,58.0580,-0.013769,0.009436
2007-05-08,2.0,57.20,57.30,57.10,57.30,183000.0,29.0,57.2123,0.012216,0.009436
2007-05-09,2.0,57.75,58.00,57.75,58.00,49500.0,17.0,57.9288,-0.009483,0.009436
2007-05-10,2.0,57.25,57.45,57.25,57.45,76500.0,15.0,57.3915,-0.006092,0.009436
2007-05-11,2.0,57.05,57.10,57.05,57.10,93000.0,9.0,57.0847,-0.004378,0.009436
2007-05-14,2.0,56.80,56.85,56.80,56.85,71000.0,19.0,56.8218,0.006157,0.009436
2007-05-15,2.0,57.15,57.20,56.90,57.20,37000.0,24.0,57.1480,-0.005245,0.009436
2007-05-16,2.0,57.00,57.15,56.90,56.90,25500.0,10.0,57.0039,0.003515,0.009436
2007-05-17,2.0,56.85,57.10,56.85,57.10,146500.0,14.0,56.9657,-0.005254,0.009436
2007-05-18,2.0,56.70,56.80,56.70,56.80,6500.0,4.0,56.7615,-0.007042,0.009436
2007-05-21,2.0,56.50,56.50,56.40,56.40,147000.0,15.0,56.4182,-0.016844,0.009436
2007-05-22,2.0,55.45,55.50,55.40,55.45,73500.0,21.0,55.4381,-0.007214,0.009436
2007-05-23,2.0,55.05,55.10,55.00,55.05,206500.0,22.0,55.0150,-0.009083,0.009436
2007-05-25,2.0,54.60,54.60,54.50,54.55,57500.0,14.0,54.5491,0.002750,0.009436
2007-05-28,2.0,54.75,54.75,54.70,54.70,65000.0,13.0,54.7069,-0.000914,0.009436
2007-05-29,2.0,54.65,54.65,54.60,54.65,161500.0,13.0,54.6053,0.002745,0.009436
2007-05-30,2.0,54.90,54.90,54.75,54.80,181000.0,35.0,54.7775,0.004562,0.009436
2007-05-31,2.0,55.10,55.15,55.00,55.05,3734500.0,75.0,55.0278,0.000000,0.009436
2007-06-01,2.0,55.45,55.45,55.05,55.05,142500.0,23.0,55.3068,-0.005450,0.009436
2007-06-04,2.0,54.80,54.85,54.75,54.75,165500.0,15.0,54.7937,-0.006393,0.009436
2007-06-05,2.0,54.45,54.45,54.25,54.40,246500.0,29.0,54.3165,0.000919,0.008447
2007-06-06,2.0,54.80,54.85,54.45,54.45,37500.0,12.0,54.7420,-0.002755,0.006961
2007-06-07,2.0,54.70,54.70,54.30,54.30,82000.0,14.0,54.5488,-0.010129,0.006669
2007-06-08,2.0,53.75,53.75,53.70,53.75,137000.0,16.0,53.7235,0.004651,0.006731
2007-06-11,2.0,54.00,54.25,53.85,54.00,149500.0,18.0,54.1189,-0.008333,0.006789
2007-06-12,2.0,53.50,53.60,53.30,53.55,79500.0,15.0,53.4821,-0.000934,0.006435
...,...,...,...,...,...,...,...,...,...,...
2018-06-15,2.0,81.10,81.10,81.05,81.10,13000.0,9.0,81.0904,-0.012330,0.009429
2018-06-19,2.0,80.15,80.20,80.10,80.10,26000.0,30.0,80.1702,0.008115,0.009413
2018-06-20,2.0,80.70,80.75,80.70,80.75,9000.0,13.0,80.7194,-0.006192,0.008983
2018-06-21,2.0,80.15,80.25,80.05,80.25,5000.0,7.0,80.1800,0.000000,0.008782
2018-06-22,2.0,80.40,80.40,80.25,80.25,4000.0,8.0,80.3625,0.000000,0.008770
2018-06-25,2.0,80.25,80.50,80.20,80.25,28000.0,31.0,80.2768,0.031153,0.010753
2018-06-26,2.0,82.75,82.75,82.65,82.75,35000.0,48.0,82.7071,0.007855,0.009861
2018-06-27,2.0,83.40,83.45,83.40,83.40,68000.0,64.0,83.4147,0.011990,0.009796
2018-06-28,2.0,84.25,84.40,84.20,84.40,20500.0,30.0,84.3439,0.001185,0.009530
2018-06-29,2.0,84.50,84.50,84.50,84.50,0.0,0.0,84.5000,-0.001183,0.009491
2018-07-03,2.0,84.45,84.50,84.40,84.40,24000.0,31.0,84.4458,0.034953,0.011534
2018-07-04,2.0,87.30,87.35,87.30,87.35,16000.0,21.0,87.3203,0.005724,0.011349
2018-07-05,2.0,87.80,87.85,87.70,87.85,20500.0,25.0,87.7902,0.001707,0.011320
2018-07-06,2.0,88.00,88.00,87.95,88.00,13500.0,19.0,87.9852,-0.000568,0.011281
2018-07-09,2.0,88.00,88.00,87.95,87.95,21000.0,25.0,87.9798,-0.005685,0.011065
2018-07-10,2.0,87.55,87.55,87.45,87.45,12500.0,20.0,87.5080,-0.008005,0.011218
2018-07-11,2.0,86.75,86.75,86.60,86.75,5500.0,9.0,86.7136,0.005187,0.011223
2018-07-12,2.0,87.20,87.20,87.10,87.20,9500.0,13.0,87.1842,0.001720,0.011179
2018-07-13,2.0,87.40,87.45,87.30,87.35,24500.0,18.0,87.3582,0.012021,0.011172
2018-07-16,2.0,88.40,88.40,88.35,88.40,36000.0,31.0,88.3986,-0.005656,0.010857
2018-07-17,2.0,87.90,87.90,87.90,87.90,1500.0,2.0,87.9000,0.004551,0.010827
2018-07-18,2.0,88.25,88.40,88.25,88.30,38500.0,45.0,88.3247,0.001699,0.010824
2018-07-19,2.0,88.50,88.55,88.45,88.45,12500.0,16.0,88.4760,0.009610,0.010802
2018-07-20,2.0,89.35,89.35,89.20,89.30,32000.0,30.0,89.2750,0.000000,0.010684
2018-07-23,2.0,89.30,89.30,89.25,89.30,18000.0,29.0,89.2764,-0.004479,0.010768
2018-07-24,2.0,88.80,89.15,88.80,88.90,20500.0,33.0,88.8854,-0.005062,0.010408
2018-07-25,2.0,88.40,88.45,88.40,88.45,11000.0,13.0,88.4318,0.000000,0.010402
2018-07-26,2.0,88.50,88.50,88.45,88.45,21000.0,28.0,88.4964,-0.005653,0.010381
2018-07-27,2.0,88.00,88.00,87.90,87.95,13000.0,18.0,87.9385,0.007959,0.010384
2018-07-30,2.0,88.70,88.75,88.65,88.65,25000.0,21.0,88.6880,0.000218,0.010381

In [19]:
SEHK_2_df.set_index('Date_key', inplace=True)
SEHK_2_df

,Name,Open,High,Low,Close,Volume,Count,VWAP,Volatility
Date_key,,,,,,,,,
2007-04-30,2,59.05,59.05,58.50,58.50,5000,6,58.6550,NaN
2007-04-30,2,58.50,58.50,58.50,58.50,1000,1,58.5000,NaN
2007-04-30,2,58.50,58.50,58.50,58.50,0,0,58.5000,NaN
2007-04-30,2,58.50,58.50,58.50,58.50,0,0,58.5000,NaN
2007-04-30,2,58.50,58.50,58.50,58.50,0,0,58.5000,NaN
2007-04-30,2,58.35,58.35,58.35,58.35,2000,1,58.3500,NaN
2007-04-30,2,58.35,58.35,58.35,58.35,0,0,58.3500,NaN
2007-04-30,2,58.35,58.35,58.35,58.35,0,0,58.3500,NaN
2007-04-30,2,58.40,58.40,58.40,58.40,25000,1,58.4000,NaN
2007-04-30,2,58.35,58.40,58.35,58.40,3000,2,58.3667,NaN
2007-04-30,2,58.40,58.40,58.40,58.40,0,0,58.4000,NaN
2007-04-30,2,58.40,58.40,58.40,58.40,0,0,58.4000,NaN
2007-04-30,2,58.40,58.40,58.40,58.40,15000,1,58.4000,NaN
2007-04-30,2,58.40,58.40,58.40,58.40,0,0,58.4000,NaN
2007-04-30,2,58.40,58.40,58.40,58.40,0,0,58.4000,NaN
2007-04-30,2,58.35,58.35,58.35,58.35,4500,2,58.3500,NaN
2007-04-30,2,58.35,58.35,58.35,58.35,0,0,58.3500,NaN
2007-04-30,2,58.35,58.35,58.35,58.35,2000,1,58.3500,NaN
2007-04-30,2,58.30,58.30,58.20,58.20,6000,3,58.2667,NaN
2007-04-30,2,58.25,58.25,58.25,58.25,2500,1,58.2500,NaN
2007-04-30,2,58.25,58.25,58.25,58.25,0,0,58.2500,NaN
2007-04-30,2,58.20,58.20,58.10,58.10,25000,4,58.1940,NaN
2007-04-30,2,58.10,58.10,58.10,58.10,22500,3,58.1000,NaN
2007-04-30,2,58.10,58.15,58.00,58.15,110000,3,58.1032,NaN
2007-04-30,2,58.10,58.10,58.10,58.10,2000,1,58.1000,NaN
2007-04-30,2,58.10,58.10,58.00,58.00,18000,3,58.0194,NaN
2007-04-30,2,58.10,58.10,58.10,58.10,1282,2,58.1000,NaN
2007-04-30,2,58.10,58.10,58.10,58.10,0,0,58.1000,NaN
2007-04-30,2,58.10,58.10,58.10,58.10,20000,1,58.1000,NaN
2007-04-30,2,58.10,58.10,58.10,58.10,5000,1,58.1000,NaN
...,...,...,...,...,...,...,...,...,...
2018-07-30,2,89.00,89.00,89.00,89.00,6500,9,89.0000,NaN
2018-07-30,2,89.00,89.00,89.00,89.00,2500,5,89.0000,NaN
2018-07-30,2,89.00,89.00,89.00,89.00,3000,6,89.0000,NaN
2018-07-30,2,89.00,89.00,89.00,89.00,2000,4,89.0000,NaN
2018-07-30,2,89.00,89.00,88.95,89.00,3500,7,88.9929,NaN
2018-07-30,2,89.00,89.00,88.95,89.00,18000,23,88.9583,NaN
2018-07-30,2,89.00,89.00,88.95,89.00,7500,13,88.9633,NaN
2018-07-30,2,89.00,89.00,88.95,89.00,3500,7,88.9857,NaN
2018-07-30,2,89.00,89.00,89.00,89.00,25000,15,89.0000,NaN
2018-07-30,2,89.00,89.00,89.00,89.00,2500,4,89.0000,NaN
2018-07-30,2,89.00,89.00,89.00,89.00,3000,6,89.0000,NaN
2018-07-30,2,89.00,89.00,89.00,89.00,3500,7,89.0000,NaN
2018-07-30,2,88.95,89.00,88.95,89.00,5000,9,88.9750,NaN
2018-07-30,2,89.00,89.00,89.00,89.00,4500,9,89.0000,NaN
2018-07-30,2,89.00,89.00,89.00,89.00,3500,7,89.0000,NaN
2018-07-30,2,89.00,89.00,88.95,89.00,20500,12,88.9610,NaN
2018-07-30,2,89.00,89.00,89.00,89.00,8500,8,89.0000,NaN
2018-07-30,2,89.00,89.00,88.95,89.00,7500,14,88.9967,NaN
2018-07-30,2,89.00,89.00,88.95,89.00,9000,13,88.9722,NaN
2018-07-30,2,89.00,89.00,88.95,89.00,9500,17,88.9737,NaN
2018-07-30,2,89.00,89.00,89.00,89.00,4500,9,89.0000,NaN
2018-07-30,2,89.00,89.00,88.95,89.00,6500,11,88.9962,NaN
2018-07-30,2,89.00,89.00,89.00,89.00,5500,9,89.0000,NaN
2018-07-30,2,89.00,89.00,89.00,89.00,7000,13,89.0000,NaN
2018-07-30,2,89.00,89.00,89.00,89.00,7000,12,89.0000,NaN
2018-07-30,2,89.00,89.00,89.00,89.00,8500,15,89.0000,NaN
2018-07-30,2,89.00,89.00,89.00,89.00,10000,17,89.0000,NaN
2018-07-30,2,88.95,88.95,88.70,88.75,70000,50,88.8839,NaN
2018-07-30,2,88.70,88.75,88.70,88.70,13500,12,88.7426,NaN
2018-07-30,2,88.70,88.75,88.65,88.65,25000,21,88.6880,NaN

In [20]:
# Merge 25-day Volatility to intraday dataset
SEHK_2_df['Volatility'] = day_SEHK_2_df['Volatility']
SEHK_2_df.fillna(SEHK_2_df['Volatility'].mean(), inplace=True)

In [21]:
# day_SEHK_2_df = SEHK_2_df.resample('B').last()
# day_SEHK_2_df
SEHK_2_df

,Name,Open,High,Low,Close,Volume,Count,VWAP,Volatility
Date_key,,,,,,,,,
2007-04-30,2,59.05,59.05,58.50,58.50,5000,6,58.6550,0.009436
2007-04-30,2,58.50,58.50,58.50,58.50,1000,1,58.5000,0.009436
2007-04-30,2,58.50,58.50,58.50,58.50,0,0,58.5000,0.009436
2007-04-30,2,58.50,58.50,58.50,58.50,0,0,58.5000,0.009436
2007-04-30,2,58.50,58.50,58.50,58.50,0,0,58.5000,0.009436
2007-04-30,2,58.35,58.35,58.35,58.35,2000,1,58.3500,0.009436
2007-04-30,2,58.35,58.35,58.35,58.35,0,0,58.3500,0.009436
2007-04-30,2,58.35,58.35,58.35,58.35,0,0,58.3500,0.009436
2007-04-30,2,58.40,58.40,58.40,58.40,25000,1,58.4000,0.009436
2007-04-30,2,58.35,58.40,58.35,58.40,3000,2,58.3667,0.009436
2007-04-30,2,58.40,58.40,58.40,58.40,0,0,58.4000,0.009436
2007-04-30,2,58.40,58.40,58.40,58.40,0,0,58.4000,0.009436
2007-04-30,2,58.40,58.40,58.40,58.40,15000,1,58.4000,0.009436
2007-04-30,2,58.40,58.40,58.40,58.40,0,0,58.4000,0.009436
2007-04-30,2,58.40,58.40,58.40,58.40,0,0,58.4000,0.009436
2007-04-30,2,58.35,58.35,58.35,58.35,4500,2,58.3500,0.009436
2007-04-30,2,58.35,58.35,58.35,58.35,0,0,58.3500,0.009436
2007-04-30,2,58.35,58.35,58.35,58.35,2000,1,58.3500,0.009436
2007-04-30,2,58.30,58.30,58.20,58.20,6000,3,58.2667,0.009436
2007-04-30,2,58.25,58.25,58.25,58.25,2500,1,58.2500,0.009436
2007-04-30,2,58.25,58.25,58.25,58.25,0,0,58.2500,0.009436
2007-04-30,2,58.20,58.20,58.10,58.10,25000,4,58.1940,0.009436
2007-04-30,2,58.10,58.10,58.10,58.10,22500,3,58.1000,0.009436
2007-04-30,2,58.10,58.15,58.00,58.15,110000,3,58.1032,0.009436
2007-04-30,2,58.10,58.10,58.10,58.10,2000,1,58.1000,0.009436
2007-04-30,2,58.10,58.10,58.00,58.00,18000,3,58.0194,0.009436
2007-04-30,2,58.10,58.10,58.10,58.10,1282,2,58.1000,0.009436
2007-04-30,2,58.10,58.10,58.10,58.10,0,0,58.1000,0.009436
2007-04-30,2,58.10,58.10,58.10,58.10,20000,1,58.1000,0.009436
2007-04-30,2,58.10,58.10,58.10,58.10,5000,1,58.1000,0.009436
...,...,...,...,...,...,...,...,...,...
2018-07-30,2,89.00,89.00,89.00,89.00,6500,9,89.0000,0.010381
2018-07-30,2,89.00,89.00,89.00,89.00,2500,5,89.0000,0.010381
2018-07-30,2,89.00,89.00,89.00,89.00,3000,6,89.0000,0.010381
2018-07-30,2,89.00,89.00,89.00,89.00,2000,4,89.0000,0.010381
2018-07-30,2,89.00,89.00,88.95,89.00,3500,7,88.9929,0.010381
2018-07-30,2,89.00,89.00,88.95,89.00,18000,23,88.9583,0.010381
2018-07-30,2,89.00,89.00,88.95,89.00,7500,13,88.9633,0.010381
2018-07-30,2,89.00,89.00,88.95,89.00,3500,7,88.9857,0.010381
2018-07-30,2,89.00,89.00,89.00,89.00,25000,15,89.0000,0.010381
2018-07-30,2,89.00,89.00,89.00,89.00,2500,4,89.0000,0.010381
2018-07-30,2,89.00,89.00,89.00,89.00,3000,6,89.0000,0.010381
2018-07-30,2,89.00,89.00,89.00,89.00,3500,7,89.0000,0.010381
2018-07-30,2,88.95,89.00,88.95,89.00,5000,9,88.9750,0.010381
2018-07-30,2,89.00,89.00,89.00,89.00,4500,9,89.0000,0.010381
2018-07-30,2,89.00,89.00,89.00,89.00,3500,7,89.0000,0.010381
2018-07-30,2,89.00,89.00,88.95,89.00,20500,12,88.9610,0.010381
2018-07-30,2,89.00,89.00,89.00,89.00,8500,8,89.0000,0.010381
2018-07-30,2,89.00,89.00,88.95,89.00,7500,14,88.9967,0.010381
2018-07-30,2,89.00,89.00,88.95,89.00,9000,13,88.9722,0.010381
2018-07-30,2,89.00,89.00,88.95,89.00,9500,17,88.9737,0.010381
2018-07-30,2,89.00,89.00,89.00,89.00,4500,9,89.0000,0.010381
2018-07-30,2,89.00,89.00,88.95,89.00,6500,11,88.9962,0.010381
2018-07-30,2,89.00,89.00,89.00,89.00,5500,9,89.0000,0.010381
2018-07-30,2,89.00,89.00,89.00,89.00,7000,13,89.0000,0.010381
2018-07-30,2,89.00,89.00,89.00,89.00,7000,12,89.0000,0.010381
2018-07-30,2,89.00,89.00,89.00,89.00,8500,15,89.0000,0.010381
2018-07-30,2,89.00,89.00,89.00,89.00,10000,17,89.0000,0.010381
2018-07-30,2,88.95,88.95,88.70,88.75,70000,50,88.8839,0.010381
2018-07-30,2,88.70,88.75,88.70,88.70,13500,12,88.7426,0.010381
2018-07-30,2,88.70,88.75,88.65,88.65,25000,21,88.6880,0.010381

In [22]:
SEHK_2_df2 = csvdf['2012':'2018-07-30'].copy()
day_SEHK_2_df2 = SEHK_2_df2.resample('B').mean()
day_SEHK_2_df2.dropna(inplace=True)
# day_SEHK_2_df2
daily_average_volume = day_SEHK_2_df2['Volume']

In [23]:
day_SEHK_2_df2

,Name,Open,High,Low,Close,Volume,Count,VWAP
Date,,,,,,,,
2012-01-03,2.0,66.015667,66.031333,66.001833,66.017833,5683.333333,2.756667,66.019005
2012-01-04,2.0,65.971833,65.978667,65.963500,65.973333,8906.666667,3.120000,65.971964
2012-01-05,2.0,66.019333,66.029167,66.014833,66.024167,3483.333333,1.750000,66.020905
2012-01-06,2.0,65.975167,65.991667,65.965000,65.981667,10335.000000,3.296667,65.977112
2012-01-09,2.0,66.129333,66.139333,66.120000,66.128833,5255.000000,2.660000,66.128860
2012-01-10,2.0,66.463833,66.478167,66.452167,66.464500,5946.666667,3.180000,66.466972
2012-01-11,2.0,66.160833,66.169833,66.150333,66.159833,8355.000000,2.990000,66.158933
2012-01-12,2.0,64.965167,64.982333,64.941667,64.960333,21728.333333,7.166667,64.960384
2012-01-13,2.0,64.277833,64.293833,64.261167,64.280833,16196.666667,5.066667,64.281433
2012-01-16,2.0,63.621333,63.634500,63.610333,63.623667,12060.000000,3.580000,63.622168
2012-01-17,2.0,63.802333,63.814833,63.788667,63.802833,11216.666667,4.553333,63.803684
2012-01-18,2.0,63.709667,63.726833,63.686667,63.708000,18208.333333,5.476667,63.703933
2012-01-19,2.0,62.288500,62.302833,62.266667,62.287833,19936.666667,6.956667,62.286532
2012-01-20,2.0,62.839333,62.857333,62.818833,62.841000,12611.666667,5.456667,62.838258
2012-01-26,2.0,62.321667,62.336333,62.302833,62.321333,15621.666667,6.243333,62.322591
2012-01-27,2.0,63.028000,63.043667,63.007000,63.026167,17721.666667,5.903333,63.024802
2012-01-30,2.0,64.001333,64.018167,63.981667,63.998167,15178.333333,6.276667,63.998798
2012-01-31,2.0,63.894667,63.910500,63.873333,63.892167,18296.666667,7.053333,63.892569
2012-02-01,2.0,63.726333,63.734333,63.712667,63.722833,7273.333333,3.050000,63.722888
2012-02-02,2.0,63.325500,63.347000,63.303833,63.318000,17680.000000,7.766667,63.323615
2012-02-03,2.0,63.162000,63.170167,63.149000,63.160333,14501.666667,4.043333,63.159767
2012-02-06,2.0,63.323000,63.340333,63.311500,63.326000,11408.333333,4.263333,63.326356
2012-02-07,2.0,63.499000,63.509333,63.490333,63.500167,8698.333333,3.256667,63.499937
2012-02-08,2.0,63.690000,63.701500,63.669000,63.681500,10373.333333,4.000000,63.687008
2012-02-09,2.0,63.487000,63.501667,63.474833,63.485000,8375.000000,3.630000,63.489512
2012-02-10,2.0,63.919833,63.938167,63.908667,63.924000,13366.666667,4.383333,63.923638
2012-02-13,2.0,64.427167,64.440000,64.411167,64.428667,10346.666667,3.453333,64.424585
2012-02-14,2.0,64.673500,64.682000,64.660500,64.671000,8361.666667,2.686667,64.671758
2012-02-15,2.0,65.097000,65.115833,65.082500,65.099000,14266.666667,5.363333,65.099515
2012-02-16,2.0,64.842500,64.855000,64.833833,64.846667,6633.333333,2.246667,64.843087
...,...,...,...,...,...,...,...,...
2018-06-15,2.0,81.236818,81.257424,81.222273,81.240909,5775.757576,6.109091,81.238908
2018-06-19,2.0,80.630909,80.655606,80.607424,80.627424,12042.424242,11.481818,80.632710
2018-06-20,2.0,80.616970,80.635152,80.604394,80.619848,5124.242424,5.378788,80.619437
2018-06-21,2.0,80.698636,80.725000,80.681364,80.702273,5163.636364,5.657576,80.699374
2018-06-22,2.0,80.222727,80.230000,80.215909,80.222121,2339.393939,1.990909,80.223363
2018-06-25,2.0,80.521212,80.539545,80.505303,80.522121,5159.090909,5.860606,80.520760
2018-06-26,2.0,81.763636,81.783788,81.745152,81.773485,15568.181818,12.087879,81.763071
2018-06-27,2.0,83.295303,83.315909,83.280455,83.298788,16478.787879,11.936364,83.297369
2018-06-28,2.0,83.393485,83.424545,83.374545,83.406970,12643.939394,10.742424,83.399184
2018-06-29,2.0,84.507794,84.523824,84.494706,84.512059,12670.588235,9.285294,84.506300
2018-07-03,2.0,83.976364,83.995000,83.965909,83.981061,9433.333333,8.787879,83.978497
2018-07-04,2.0,86.782273,86.826061,86.753939,86.795455,17060.606061,11.378788,86.785025
2018-07-05,2.0,87.269242,87.296667,87.239545,87.275152,13609.090909,11.045455,87.268155
2018-07-06,2.0,87.981970,88.004545,87.958485,87.982727,14086.363636,11.021212,87.980307
2018-07-09,2.0,88.035000,88.048333,88.020909,88.033030,9613.636364,6.372727,88.034411
2018-07-10,2.0,87.712424,87.728030,87.694545,87.708788,8453.030303,7.448485,87.710302
2018-07-11,2.0,86.700152,86.707879,86.682273,86.694545,6684.848485,4.048485,86.695986
2018-07-12,2.0,87.306667,87.314242,87.295303,87.303485,3537.878788,4.054545,87.305283
2018-07-13,2.0,87.651667,87.663485,87.639242,87.651970,4166.666667,4.709091,87.651411
2018-07-16,2.0,88.224091,88.243333,88.212727,88.232727,5096.969697,5.354545,88.226090
2018-07-17,2.0,88.174242,88.183636,88.165152,88.176061,2624.242424,3.030303,88.173693
2018-07-18,2.0,88.315000,88.329545,88.307576,88.322273,5012.121212,5.369697,88.318043
2018-07-19,2.0,88.444242,88.453485,88.431818,88.439242,5848.484848,4.669697,88.443508
2018-07-20,2.0,88.961970,88.982879,88.933636,88.965303,9183.333333,8.642424,88.958610
2018-07-23,2.0,89.248030,89.257424,89.240909,89.248939,4750.000000,3.590909,89.248645
2018-07-24,2.0,88.909848,88.930455,88.895152,88.912424,6342.424242,7.206061,88.908431
2018-07-25,2.0,88.588788,88.610152,88.573636,88.590303,5104.545455,5.860606,88.588886
2018-07-26,2.0,88.279848,88.298939,88.261818,88.281212,4490.909091,4.463636,88.277667
2018-07-27,2.0,87.913485,87.932273,87.895000,87.916212,4021.212121,5.006061,87.911414
2018-07-30,2.0,88.626818,88.636515,88.615909,88.625909,4795.454545,4.706061,88.624118

In [25]:
previous_daily_average_volume = daily_average_volume.shift(1)

In [26]:
previous_daily_average_volume.fillna(previous_daily_average_volume.mean(), inplace=True)
previous_daily_average_volume

Date
2012-01-03     8068.197153
2012-01-04     5683.333333
2012-01-05     8906.666667
2012-01-06     3483.333333
2012-01-09    10335.000000
2012-01-10     5255.000000
2012-01-11     5946.666667
2012-01-12     8355.000000
2012-01-13    21728.333333
2012-01-16    16196.666667
2012-01-17    12060.000000
2012-01-18    11216.666667
2012-01-19    18208.333333
2012-01-20    19936.666667
2012-01-26    12611.666667
2012-01-27    15621.666667
2012-01-30    17721.666667
2012-01-31    15178.333333
2012-02-01    18296.666667
2012-02-02     7273.333333
2012-02-03    17680.000000
2012-02-06    14501.666667
2012-02-07    11408.333333
2012-02-08     8698.333333
2012-02-09    10373.333333
2012-02-10     8375.000000
2012-02-13    13366.666667
2012-02-14    10346.666667
2012-02-15     8361.666667
2012-02-16    14266.666667
                  ...
2018-06-15     3803.030303
2018-06-19     5775.757576
2018-06-20    12042.424242
2018-06-21     5124.242424
2018-06-22     5163.636364
2018-06-25     2339.393939
2018-06-26     5159.090909
2018-06-27    15568.181818
2018-06-28    16478.787879
2018-06-29    12643.939394
2018-07-03    12670.588235
2018-07-04     9433.333333
2018-07-05    17060.606061
2018-07-06    13609.090909
2018-07-09    14086.363636
2018-07-10     9613.636364
2018-07-11     8453.030303
2018-07-12     6684.848485
2018-07-13     3537.878788
2018-07-16     4166.666667
2018-07-17     5096.969697
2018-07-18     2624.242424
2018-07-19     5012.121212
2018-07-20     5848.484848
2018-07-23     9183.333333
2018-07-24     4750.000000
2018-07-25     6342.424242
2018-07-26     5104.545455
2018-07-27     4490.909091
2018-07-30     4021.212121
Name: Volume, Length: 1617, dtype: float64

In [27]:
daily_average_volume

Date
2012-01-03     5683.333333
2012-01-04     8906.666667
2012-01-05     3483.333333
2012-01-06    10335.000000
2012-01-09     5255.000000
2012-01-10     5946.666667
2012-01-11     8355.000000
2012-01-12    21728.333333
2012-01-13    16196.666667
2012-01-16    12060.000000
2012-01-17    11216.666667
2012-01-18    18208.333333
2012-01-19    19936.666667
2012-01-20    12611.666667
2012-01-26    15621.666667
2012-01-27    17721.666667
2012-01-30    15178.333333
2012-01-31    18296.666667
2012-02-01     7273.333333
2012-02-02    17680.000000
2012-02-03    14501.666667
2012-02-06    11408.333333
2012-02-07     8698.333333
2012-02-08    10373.333333
2012-02-09     8375.000000
2012-02-10    13366.666667
2012-02-13    10346.666667
2012-02-14     8361.666667
2012-02-15    14266.666667
2012-02-16     6633.333333
                  ...
2018-06-15     5775.757576
2018-06-19    12042.424242
2018-06-20     5124.242424
2018-06-21     5163.636364
2018-06-22     2339.393939
2018-06-25     5159.090909
2018-06-26    15568.181818
2018-06-27    16478.787879
2018-06-28    12643.939394
2018-06-29    12670.588235
2018-07-03     9433.333333
2018-07-04    17060.606061
2018-07-05    13609.090909
2018-07-06    14086.363636
2018-07-09     9613.636364
2018-07-10     8453.030303
2018-07-11     6684.848485
2018-07-12     3537.878788
2018-07-13     4166.666667
2018-07-16     5096.969697
2018-07-17     2624.242424
2018-07-18     5012.121212
2018-07-19     5848.484848
2018-07-20     9183.333333
2018-07-23     4750.000000
2018-07-24     6342.424242
2018-07-25     5104.545455
2018-07-26     4490.909091
2018-07-27     4021.212121
2018-07-30     4795.454545
Name: Volume, Length: 1617, dtype: float64

In [28]:
SEHK_2_df['Daily_Average_Volume'] = daily_average_volume.round(0).fillna(0)

In [29]:
SEHK_2_df['Previous_Daily_Average_Volume'] = previous_daily_average_volume.round(0).fillna(0)

In [30]:
SEHK_2_df['Trading Volume'] = SEHK_2_df['Volume'][:] / SEHK_2_df['Count'][:]

In [31]:
# Rounding volume
SEHK_2_df['Trading Volume'] = SEHK_2_df['Trading Volume'].round(0).fillna(0)

In [32]:
SEHK_2_df['Size'] = SEHK_2_df['Trading Volume'][:] / SEHK_2_df['Previous_Daily_Average_Volume'][:]

In [33]:
SEHK_2_df['Volatility'] = SEHK_2_df['Volatility'].round(4).fillna(0)
SEHK_2_df['Size'] = SEHK_2_df['Size'].round(4).fillna(0)

In [34]:
SEHK_2_df['POV'] = SEHK_2_df['Trading Volume'][:] / SEHK_2_df['Trading Volume'].rolling(30).sum()

In [35]:
SEHK_2_df['POV'].fillna(SEHK_2_df['POV'].mean(), inplace=True)

In [36]:
SEHK_2_df['Cost'] = (np.log(SEHK_2_df['VWAP'][:]) - (np.log((SEHK_2_df['High'][:] + SEHK_2_df['Low'][:]) / 2))).abs()*10000
SEHK_2_df['Cost'] = SEHK_2_df['Cost'].round(4)

In [47]:
SEHK_2_df

,Name,Open,High,Low,Close,Volume,Count,VWAP,Volatility,Daily_Average_Volume,Previous_Daily_Average_Volume,Trading Volume,Size,POV,Cost
Date_key,,,,,,,,,,,,,,,
2007-04-30,2,59.05,59.05,58.50,58.50,5000,6,58.6550,0.0094,NaN,NaN,833.0,0.0000,0.033592,20.4377
2007-04-30,2,58.50,58.50,58.50,58.50,1000,1,58.5000,0.0094,NaN,NaN,1000.0,0.0000,0.033592,0.0000
2007-04-30,2,58.50,58.50,58.50,58.50,0,0,58.5000,0.0094,NaN,NaN,0.0,0.0000,0.033592,0.0000
2007-04-30,2,58.50,58.50,58.50,58.50,0,0,58.5000,0.0094,NaN,NaN,0.0,0.0000,0.033592,0.0000
2007-04-30,2,58.50,58.50,58.50,58.50,0,0,58.5000,0.0094,NaN,NaN,0.0,0.0000,0.033592,0.0000
2007-04-30,2,58.35,58.35,58.35,58.35,2000,1,58.3500,0.0094,NaN,NaN,2000.0,0.0000,0.033592,0.0000
2007-04-30,2,58.35,58.35,58.35,58.35,0,0,58.3500,0.0094,NaN,NaN,0.0,0.0000,0.033592,0.0000
2007-04-30,2,58.35,58.35,58.35,58.35,0,0,58.3500,0.0094,NaN,NaN,0.0,0.0000,0.033592,0.0000
2007-04-30,2,58.40,58.40,58.40,58.40,25000,1,58.4000,0.0094,NaN,NaN,25000.0,0.0000,0.033592,0.0000
2007-04-30,2,58.35,58.40,58.35,58.40,3000,2,58.3667,0.0094,NaN,NaN,1500.0,0.0000,0.033592,1.4219
2007-04-30,2,58.40,58.40,58.40,58.40,0,0,58.4000,0.0094,NaN,NaN,0.0,0.0000,0.033592,0.0000
2007-04-30,2,58.40,58.40,58.40,58.40,0,0,58.4000,0.0094,NaN,NaN,0.0,0.0000,0.033592,0.0000
2007-04-30,2,58.40,58.40,58.40,58.40,15000,1,58.4000,0.0094,NaN,NaN,15000.0,0.0000,0.033592,0.0000
2007-04-30,2,58.40,58.40,58.40,58.40,0,0,58.4000,0.0094,NaN,NaN,0.0,0.0000,0.033592,0.0000
2007-04-30,2,58.40,58.40,58.40,58.40,0,0,58.4000,0.0094,NaN,NaN,0.0,0.0000,0.033592,0.0000
2007-04-30,2,58.35,58.35,58.35,58.35,4500,2,58.3500,0.0094,NaN,NaN,2250.0,0.0000,0.033592,0.0000
2007-04-30,2,58.35,58.35,58.35,58.35,0,0,58.3500,0.0094,NaN,NaN,0.0,0.0000,0.033592,0.0000
2007-04-30,2,58.35,58.35,58.35,58.35,2000,1,58.3500,0.0094,NaN,NaN,2000.0,0.0000,0.033592,0.0000
2007-04-30,2,58.30,58.30,58.20,58.20,6000,3,58.2667,0.0094,NaN,NaN,2000.0,0.0000,0.033592,2.8665
2007-04-30,2,58.25,58.25,58.25,58.25,2500,1,58.2500,0.0094,NaN,NaN,2500.0,0.0000,0.033592,0.0000
2007-04-30,2,58.25,58.25,58.25,58.25,0,0,58.2500,0.0094,NaN,NaN,0.0,0.0000,0.033592,0.0000
2007-04-30,2,58.20,58.20,58.10,58.10,25000,4,58.1940,0.0094,NaN,NaN,6250.0,0.0000,0.033592,7.5638
2007-04-30,2,58.10,58.10,58.10,58.10,22500,3,58.1000,0.0094,NaN,NaN,7500.0,0.0000,0.033592,0.0000
2007-04-30,2,58.10,58.15,58.00,58.15,110000,3,58.1032,0.0094,NaN,NaN,36667.0,0.0000,0.033592,4.8546
2007-04-30,2,58.10,58.10,58.10,58.10,2000,1,58.1000,0.0094,NaN,NaN,2000.0,0.0000,0.033592,0.0000
2007-04-30,2,58.10,58.10,58.00,58.00,18000,3,58.0194,0.0094,NaN,NaN,6000.0,0.0000,0.033592,5.2727
2007-04-30,2,58.10,58.10,58.10,58.10,1282,2,58.1000,0.0094,NaN,NaN,641.0,0.0000,0.033592,0.0000
2007-04-30,2,58.10,58.10,58.10,58.10,0,0,58.1000,0.0094,NaN,NaN,0.0,0.0000,0.033592,0.0000
2007-04-30,2,58.10,58.10,58.10,58.10,20000,1,58.1000,0.0094,NaN,NaN,20000.0,0.0000,0.033592,0.0000
2007-04-30,2,58.10,58.10,58.10,58.10,5000,1,58.1000,0.0094,NaN,NaN,5000.0,0.0000,0.036195,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-07-30,2,89.00,89.00,89.00,89.00,6500,9,89.0000,0.0104,4795.0,4021.0,722.0,0.1796,0.041621,0.0000
2018-07-30,2,89.00,89.00,89.00,89.00,2500,5,89.0000,0.0104,4795.0,4021.0,500.0,0.1243,0.031458,0.0000
2018-07-30,2,89.00,89.00,89.00,89.00,3000,6,89.0000,0.0104,4795.0,4021.0,500.0,0.1243,0.030499,0.0000
2018-07-30,2,89.00,89.00,89.00,89.00,2000,4,89.0000,0.0104,4795.0,4021.0,500.0,0.1243,0.030813,0.0000
2018-07-30,2,89.00,89.00,88.95,89.00,3500,7,88.9929,0.0104,4795.0,4021.0,500.0,0.1243,0.029892,2.0116
2018-07-30,2,89.00,89.00,88.95,89.00,18000,23,88.9583,0.0104,4795.0,4021.0,783.0,0.1947,0.046032,1.8771
2018-07-30,2,89.00,89.00,88.95,89.00,7500,13,88.9633,0.0104,4795.0,4021.0,577.0,0.1435,0.032808,1.3151
2018-07-30,2,89.00,89.00,88.95,89.00,3500,7,88.9857,0.0104,4795.0,4021.0,500.0,0.1243,0.027644,1.2025
2018-07-30,2,89.00,89.00,89.00,89.00,25000,15,89.0000,0.0104,4795.0,4021.0,1667.0,0.4146,0.084388,0.0000
2018-07-30,2,89.00,89.00,89.00,89.00,2500,4,89.0000,0.0104,4795.0,4021.0,625.0,0.1554,0.030669,0.0000
2018-07-30,2,89.00,89.00,89.00,89.00,3000,6,89.0000,0.0104,4795.0,4021.0,500.0,0.1243,0.024840,0.0000
2018-07-30,2,89.00,89.00,89.00,89.00,3500,7,89.0000,0.0104,4795.0,4021.0,500.0,0.1243,0.024238,0.0000
2018-07-30,2,88.95,89.00,88.95,89.00,5000,9,88.9750,0.0104,4795.0,4021.0,556.0,0.1383,0.026879,0.0000
2018-07-30,2,89.00,89.00,89.00,89.00,4500,9,89.0000,0.0104,4795.0,4021.0,500.0,0.1243,0.026199,0.0000
2018-07-30,2,89.00,89.00,89.00,89.00,3500,7,89.0000,0.0104,4795.0,4021.0,500.0,0.1243,0.026199,0.0000
2018-07-30,2,89.00,89.00,88.95,89.00,20500,12,88.9610,0.0104,4795.0,4021.0,1708.0,0.4248,0.084167,1.5736
2018-07-30,2,89.00,89.00,89.00,89.00,8500,8,89.0000,0.0104,4795.0,4021.0,1062.0,0.2641,0.050923,0.0000
2018-07-30,2,89.00,89.00,88.95,89.00,7500,14,88.9967,0.0104,4795.0,4021.0,536.0,0.1333,0.025657,2.4386
2018-07-30,2,89.00,89.00,88.95,89.00,9000,13,88.9722,0.0104,4795.0,4021.0,692.0,0.1721,0.032952,0.3147
2018-07-30,2,89.00,89.00,88.95,89.00,9500,17,88.9737,0.0104,4795.0,4021.0,559.0,0.1390,0.027039,0.1461
2018-07-30,2,89.00,89.00,89.00,89.00,4500,9,89.0000,0.0104,4795.0,4021.0,500.0,0.1243,0.024632,0.0000
2018-07-30,2,89.00,89.00,88.95,89.00,6500,11,88.9962,0.0104,4795.0,4021.0,591.0,0.1470,0.029246,2.3824
2018-07-30,2,89.00,89.00,89.00,89.00,5500,9,89.0000,0.0104,4795.0,4021.0,611.0,0.1520,0.030320,0.0000
2018-07-30,2,89.00,89.00,89.00,89.00,7000,13,89.0000,0.0104,4795.0,4021.0,538.0,0.1338,0.026869,0.0000
2018-07-30,2,89.00,89.00,89.00,89.00,7000,12,89.0000,0.0104,4795.0,4021.0,583.0,0.1450,0.029178,0.0000
2018-07-30,2,89.00,89.00,89.00,89.00,8500,15,89.0000,0.0104,4795.0,4021.0,567.0,0.1410,0.028460,0.0000
2018-07-30,2,89.00,89.00,89.00,89.00,10000,17,89.0000,0.0104,4795.0,4021.0,588.0,0.1462,0.029631,0.0000
2018-07-30,2,88.95,88.95,88.70,88.75,70000,50,88.8839,0.0104,4795.0,4021.0,1400.0,0.3482,0.067958,6.6288
2018-07-30,2,88.70,88.75,88.70,88.70,13500,12,88.7426,0.0104,4795.0,4021.0,1125.0,0.2798,0.053315,1.9835
2018-07-30,2,88.70,88.75,88.65,88.65,25000,21,88.6880,0.0104,4795.0,4021.0,1190.0,0.2959,0.054889,1.3530

In [49]:
SEHK_2_df[SEHK_2_df['Volume'] != 0].count()

Name                             654262
Open                             654262
High                             654262
Low                              654262
Close                            654262
Volume                           654262
Count                            654262
VWAP                             654262
Volatility                       654262
Daily_Average_Volume             410348
Previous_Daily_Average_Volume    410348
Trading Volume                   654262
Size                             654262
POV                              654262
Cost                             654262
dtype: int64

In [257]:
SEHK_2_data = SEHK_2_df[['Size', 'Volatility', 'POV', 'Cost']]

In [258]:
SEHK_2_data.reset_index(inplace=True, drop=True)

In [264]:
SEHK_2_data.to_csv('SEHK_2_MIC.csv', index=False)

In [ ]:
SEHK_2_data

In [225]:
test = SEHK_2_data.copy()
test2 = SEHK_2_data.copy()

In [223]:
test.groupby(['Volatility']).mean().reset_index()

     Volatility      Size       POV      Cost
0        0.0031  0.192342  0.033327  0.966314
1        0.0033  0.263332  0.032546  0.635729
2        0.0034  0.277869  0.033692  1.509272
3        0.0035  0.216548  0.033584  1.027598
4        0.0036  0.196006  0.033279  1.286863
5        0.0037  0.191576  0.032883  1.536866
6        0.0038  0.158953  0.033802  0.792247
7        0.0039  0.165226  0.033382  1.288476
8        0.0040  0.200289  0.033608  1.028008
9        0.0041  0.159703  0.033688  1.081734
10       0.0042  0.165725  0.033348  1.129123
11       0.0043  0.202807  0.033825  1.195394
12       0.0044  0.163096  0.033419  0.983701
13       0.0045  0.196156  0.033408  1.176320
14       0.0046  0.218174  0.033631  1.231201
15       0.0047  0.173956  0.033650  1.135066
16       0.0048  0.163295  0.033674  0.746843
17       0.0049  0.164584  0.033643  0.884969
18       0.0050  0.159697  0.033500  0.972267
19       0.0051  0.182008  0.033652  1.080137
20       0.0052  0.186175  0.033507  1.207480
21       0.0053  0.087717  0.033382  0.882077
22       0.0054  0.118037  0.033681  0.932472
23       0.0055  0.143110  0.033835  1.124120
24       0.0056  0.191268  0.033438  1.072712
25       0.0057  0.206274  0.033729  1.242521
26       0.0058  0.147871  0.033170  1.108998
27       0.0059  0.198397  0.033304  1.373884
28       0.0060  0.185326  0.033491  1.365769
29       0.0061  0.208843  0.033578  1.224759
..          ...       ...       ...       ...
72       0.0104  0.163146  0.033687  1.587822
73       0.0105  0.199352  0.033422  1.639023
74       0.0106  0.167928  0.033334  1.452630
75       0.0107  0.098652  0.033414  1.896291
76       0.0108  0.145277  0.033766  1.595005
77       0.0109  0.149718  0.033098  1.215360
78       0.0110  0.162087  0.033088  1.872683
79       0.0111  0.155263  0.033781  2.009550
80       0.0112  0.149084  0.033490  1.525186
81       0.0113  0.136310  0.033454  1.843908
82       0.0114  0.176348  0.034001  1.430474
83       0.0115  0.175941  0.033135  1.155404
84       0.0116  0.155892  0.033477  1.520191
85       0.0117  0.187921  0.033512  1.473860
86       0.0118  0.225693  0.033038  1.628740
87       0.0119  0.260830  0.033786  1.478663
88       0.0120  0.186118  0.033245  1.484533
89       0.0121  0.205677  0.033696  1.605722
90       0.0122  0.146950  0.033316  1.546608
91       0.0123  0.239898  0.033062  1.415353
92       0.0124  0.123023  0.033453  1.563072
93       0.0125  0.248348  0.032849  1.482573
94       0.0126  0.178428  0.033306  1.565470
95       0.0127  0.167692  0.034185  1.114380
96       0.0128  0.082289  0.033182  2.056520
97       0.0129  0.108138  0.033522  2.185230
98       0.0132  0.516679  0.034065  2.088487
99       0.0133  0.135777  0.033883  2.054045
100      0.0134  0.146706  0.033600  1.519134
101      0.0141  0.249932  0.032779  1.957360

[102 rows x 4 columns]